// ===== THE ARCHHAG (95f-archhag.js, build 308). Matt: "yes the archhag wakes the topiaries", "shes going to be the boss for the cloister", "more legendary jars, like 30", "when she first comes in she will
// cast and ressurect stickmen to fight for her. they are alarmingly faster that most mobs. she has a two phase healthbar. once the first one is gone she animates the topiaries", "let her stickmen run
// ahead but she walks more slowly staying back and casting". Checked on the Cloister Court: her four clips load onto one model; spawned, her arrival cast raises ten stickmen, about twice a goblin's
// speed while she is slow; a blow that would empty her first bar stops at the line, she turns to phase two, untouchable for her cast, and every topiary leaves its bed as a hopping mob on a lane; a
// cast curses a tower in reach (5 s, chains); killing her (the Heartroots kept topped up throughout: the test has no defenders, and the run ending would stop everything); plays her fall (body kept), puts every hopping topiary to sleep off the field, and bursts 30 Legendary jars; no page errors.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8963,{dist:process.env.DIST||"./dist"});
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const errors=[];
const ctx=await browser.newContext({viewport:{width:900,height:560}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e)));
await page.goto("http://127.0.0.1:8963/?silent&nogate&map=2",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__archhag&&window.__archhag.ensure&&window.__courtdecor&&window.__courtdecor.topiList,null,{timeout:120000});
await page.evaluate(()=>{ const d=window.__dd; try{ window.__trainer.skip(); }catch(e){} d.start(); d.step(1/60,10); window.__archhag.ensure(); });
for(let i=0;i<400;i++){ const ok=await page.evaluate(()=>{ window.__dd.step(1/60,1); window.__dd.S.crystal=window.__dd.S.crystal2=1e6; return window.__archhag.loaded()&&window.__archhag.stickModel().real&&window.__archhag.rigsReady()&&window.__courtdecor.topiList().length>=12; }); if(ok) break; await sleep(80); }
const a=await page.evaluate(()=>({ loaded:window.__archhag.loaded(), topi:window.__courtdecor.topiList().length }));
check("her four clips load onto one model and the court's twelve topiaries stand ready",a.loaded&&a.topi===12,JSON.stringify(a));
const sm=await page.evaluate(()=>window.__archhag.stickModel());
check("build 312: the stickmen are Matt's own rigged moss stickmen (Walking and Running, and his two-fisted punch to attack), fetched with her model -- not the code-built twig men",sm.real&&['walk','run','attack'].every(k=>sm.clips.includes(k))&&/punch/i.test(sm.attack),JSON.stringify(sm));
const b=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) d.kill(e); d.step(1/60,3); d.addMana(9000); d.setHero(-90,-90,0);
  d.S.crystal=d.S.crystal2=1e6; const e=window.__archhag.spawn(); if(!e) return {spawned:false}; const clips=Object.keys(e.mdl.actions); const L=d.lanes(); const gateDist=Math.min(...Object.values(L).map(l=>Math.hypot(e.x-d.cw(l.cx),e.z-d.cwz(l.cz)))); const midDist=Math.hypot(e.x-(d.cw(21)+d.cw(22))/2,e.z-(d.cwz(21)+d.cwz(22))/2); const y0=e.mdl.g.position.y; const heartD=Math.min(Math.hypot(e.x,e.z),Math.hypot(e.x-d.cw(11),e.z-d.cwz(28)));
  let at9=-1; for(let i=0;i<60*13&&window.__archhag.sticks()<10;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; if(i===60*9) at9=window.__archhag.sticks(); }   /* build 320: the first raise comes ~10 s in */
  for(let i=0;i<60;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; }
  const sticks=d.enemies.filter(x=>x.kind==='stickman'&&!x.dead), rigged=sticks.filter(x=>x.mdl&&x.mdl.actions&&x.mdl.actions.run).length, legScale=(()=>{ const x=sticks.find(q=>q.mdl&&q.mdl.actions&&q.mdl.actions.run); if(!x) return 0; const A=x.mdl.actions; return +Math.max(A.run.isRunning()?A.run.timeScale:0,A.walk.isRunning()?A.walk.timeScale:0).toFixed(2); })(), gob=d.spawn('goblin',Object.keys(d.lanes())[0]); const gspd=gob.spd; d.kill(gob);
  return { spawned:true, clips, gateDist:+gateDist.toFixed(1), midDist:+midDist.toFixed(1), heartD:+heartD.toFixed(1), at9, startsUnder:y0<-2, sticks:sticks.length, rigged, legScale, stickSpd:+(sticks.reduce((s,x)=>s+x.spd,0)/Math.max(1,sticks.length)).toFixed(2), goblinSpd:+gspd.toFixed(2), hagSpd:+e.spd.toFixed(2), topiAwake:window.__archhag.awake() }; });
check("build 320 (Matt: \"move the arch hag back near one of the doors and let her walk again, that will be scary\"): she rises out of the ground just inside a door, far from both Heartroots (the long walk in)",b.spawned&&b.startsUnder&&b.gateDist<8&&b.heartD>=25,JSON.stringify({gate:b.gateDist,heart:b.heartD,under:b.startsUnder}));
check("spawned, no stickmen for the first ~9 s (build 320: \"after about 10 seconds not right away\"), then her cast raises ten, nearly twice a goblin's speed, while she walks slowly (and the garden still sleeps)",b.spawned&&b.at9===0&&b.clips.includes('death')&&b.clips.includes('idle')&&b.sticks===10&&b.rigged===10&&b.legScale>.7&&b.legScale<3&&b.stickSpd>b.goblinSpd*1.6&&b.hagSpd<b.goblinSpd*.5&&b.topiAwake===0,JSON.stringify(b));
const pf=await page.evaluate(()=>{ const d=window.__dd, H=window.__archhag; const st=d.enemies.find(x=>x.kind==='stickman'&&!x.dead); if(!st) return {stick:false}; d.kill(st);
  const step=n=>{ for(let i=0;i<n;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } }; step(8); const early=H.poofs().slice(); step(22); const mid=H.poofs().slice(); step(70); const late=H.poofs().length;
  return { stick:true, early, mid, late }; });
check("build 312 (Matt: when the stickman dies he just poofs into a cloud of green glow and fades away): a killed stickman bursts into a cloud of green glow, his body fading into it within half a second, the cloud gone by two",pf.stick&&pf.early.length===1&&pf.early[0].bits>=10&&pf.early[0].body<1&&pf.mid.length===1&&pf.mid[0].body===0&&pf.late===0,JSON.stringify(pf));
const cc=await page.evaluate(()=>{ const d=window.__dd, e=d.enemies.find(x=>x.kind==='archhag'&&!x.dead); const x0=e.x, z0=e.z; if(d.hurt) d.hurt(e,5,6,6); const sq=e.squash; e.holdT=2; e.crawlT=2; e.chillT=2; d.step(1/60,1); return { squash:sq, hold:e.holdT, crawl:e.crawlT, chill:e.chillT, moved:+Math.hypot(e.x-x0,e.z-z0).toFixed(2) }; });
check("build 318 (Matt: she needs to ignore any knockback or interruption): a hit neither shoves nor squashes her, and roots, the Hourglass and chill cannot pin her",cc.squash===0&&cc.hold===0&&cc.crawl===0&&cc.chill===0&&cc.moved<.3,JSON.stringify(cc));
const bo=await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*3.5;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } const plain=d.enemies.filter(x=>!x.dead&&(x.kind==='goblin'||x.kind==='orc')); const ranged=d.enemies.filter(x=>!x.dead&&(x.kind==='archer'||x.kind==='troll'||x.kind==='trollboss')).length;
  return { goblins:plain.filter(x=>x.kind==='goblin').length, orcs:plain.filter(x=>x.kind==='orc').length, ranged, left:window.__archhag.bolusLeft() }; });
check("build 322 (Matt: when she calls her first stickmen give a bolus of 30 mobs, no ranged): with her first raise 20 goblins and 10 orcs pour in through the doors, nothing that shoots",bo.goblins>=20&&bo.orcs>=10&&bo.ranged===0&&bo.left===0,JSON.stringify(bo));
const rp=await page.evaluate(()=>{ const d=window.__dd, H=window.__archhag; const run=sec=>{ for(let i=0;i<60*sec;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } }; const s0=H.sticks(); run(10.5); const s1=H.sticks(); run(10.5); const s2=H.sticks(); run(10.5); const s3=H.sticks(); return { s0, s1, s2, s3 }; });
check("build 320 (Matt: \"then repeat until initial hp bar is gone\"): another ten every 10 s through her first bar, never more than 30 of them at once",rp.s1===rp.s0+10&&rp.s2===rp.s1+10&&rp.s3===30,JSON.stringify(rp));
const c=await page.evaluate(()=>{ const d=window.__dd, e=d.enemies.find(x=>x.kind==='archhag'&&!x.dead); const max=e.max; if(d.hurt) d.hurt(e,max*.9,0,0); else e.hp-=max*.9; d.step(1/60,2);
  const afterHit={hp:+(e.hp/max).toFixed(3),phase:e.phase,shield:+(e.shield||0).toFixed(2)}; const hp0=e.hp; if(d.hurt) d.hurt(e,50,0,0); const shielded=e.hp===hp0;
  const vis0=window.__courtdecor.topiList().filter(t=>t.mesh.visible).length;
  for(let i=0;i<60*6&&window.__archhag.awake()<12;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } for(let i=0;i<60;i++) d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6;
  const mobs=d.enemies.filter(x=>x.topi&&!x.dead); return { afterHit, shielded:!!d.hurt?shielded:'n/a', vis0, vis1:window.__courtdecor.topiList().filter(t=>t.mesh.visible).length, awake:window.__archhag.awake(), onLane:mobs.filter(x=>!x.leap).length, kinds:[...new Set(mobs.map(x=>x.kind))] }; });
check("a blow that would empty her first bar stops at the line: phase two, untouchable while she casts, and every topiary leaves its bed as a hopping mob on a lane (witch, fighter, ranger)",c.afterHit.hp===.5&&c.afterHit.phase===2&&c.afterHit.shield>0&&c.shielded!==false&&c.vis0===12&&c.vis1===0&&c.awake===12&&c.onLane===12&&c.kinds.length===3,JSON.stringify(c));
const np=await page.evaluate(()=>{ const d=window.__dd, H=window.__archhag; for(const x of d.enemies) if(x.kind==='stickman') d.kill(x); for(let i=0;i<60;i++) d.step(1/60,1); const s0=H.sticks(); for(let i=0;i<60*21;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } return { s0, s1:H.sticks() }; });
check("build 320: once her first bar is gone she raises no more stickmen",np.s0===0&&np.s1===0,JSON.stringify(np));
const lu=await page.evaluate(()=>{ const d=window.__dd, H=window.__archhag; const mobs=d.enemies.filter(x=>x.topi&&!x.dead&&!x.leap); let maxLift=0; const playing=new Set();
  for(let i=0;i<90;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; for(const e of mobs){ if(e.dead) continue; maxLift=Math.max(maxLift,Math.abs(e.mdl.g.position.y-e.y)); const A=e.mdl.actions||{}; for(const k in A) if(A[k].isRunning()) playing.add(k); } }
  return { plinths:H.plinths(), mobs:mobs.length, rigged:mobs.filter(e=>e.mdl.actions&&e.mdl.actions.walk&&e.mdl.actions.attack&&!e.mdl.g.getObjectByName('topiPivot')).length, maxLift:+maxLift.toFixed(3), playing:[...playing] }; });
check("build 324 (Matt: the topiaries rigged by Bob): every stone pedestal stays in its bed and the figures that step off are Bob's rigged ones, walking on their own legs (Walk/Attack clips, no hop, no sway)",lu.plinths===12&&lu.mobs>=10&&lu.rigged===lu.mobs&&lu.maxLift<.05&&lu.playing.includes('walk'),JSON.stringify(lu));
const gr=await page.evaluate(()=>{ const d=window.__dd, H=window.__archhag, e=d.enemies.find(x=>x.kind==='archhag'&&!x.dead); const L=Object.keys(d.lanes())[0]; const near=[]; for(let i=0;i<4;i++){ const g=d.spawn('goblin',L); g.x=e.x+Math.cos(i*1.6)*3; g.z=e.z+Math.sin(i*1.6)*3; g.spd=0; g.hp=g.max=9999; near.push(g); }   /* four goblins at her side (since build 320 she starts at a door, away from the garden's mobs) */
  const sc0=near.map(x=>x.sc); H.castGrow(); let grown=[], sparks=0; for(let i=0;i<60*3.2;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; sparks=Math.max(sparks,H.sparks()); } grown=H.grown(); const big=near.filter(x=>!x.dead).map((x,i)=>+(x.sc/sc0[near.indexOf(x)]).toFixed(2));
  for(let i=0;i<60*12;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } const back=near.filter(x=>!x.dead).map(x=>+(x.sc/sc0[near.indexOf(x)]).toFixed(2)); H.castGrow(); for(let i=0;i<60*3.2;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } const again=near.filter(x=>!x.dead).map(x=>+(x.sc/sc0[near.indexOf(x)]).toFixed(2));
  return { near:near.length, grown:grown.length, big, back, again, sparks }; });
check("build 318 (Matt: a spell that poofs green and gold and mobs temporarily double in size): her GROW cast bursts green-and-gold sparks and every mob near her swells to double -- and (build 321: \"leave big\") stays double 12 s later; a second cast never takes it past 2x",gr.near>0&&gr.grown>0&&gr.sparks>20&&gr.big.length>0&&gr.big.every(f=>f>1.9&&f<2.1)&&gr.back.every(f=>f>1.9&&f<2.1)&&gr.again.every(f=>f>1.9&&f<2.1),JSON.stringify(gr));
const t=await page.evaluate(()=>{ const d=window.__dd, e=d.enemies.find(x=>x.kind==='archhag'&&!x.dead);
  let tw=null; for(let r=1;r<6&&!tw;r++) for(let dx=-r;dx<=r&&!tw;dx++) for(let dz=-r;dz<=r&&!tw;dz++){ const n0=d.defs.length; try{ d.placeDefAt('harpoon',e.x+dx*2,e.z+dz*2,0); }catch(err){} if(d.defs.length>n0) tw=d.defs[d.defs.length-1]; }
  if(!tw) return {tower:false}; let cursed=false, cdHeld=0; for(let i=0;i<60*14&&!cursed;i++){ d.setHero(-90,-90,0); d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; if(tw.curseT>0){ cursed=true; cdHeld=tw.cd; } }
  return { tower:true, cursed, cdHeld:+cdHeld.toFixed(2), chains:!!tw.curseFx }; });
check("a cast curses a tower in reach: purple chains, its next shot held off for about 5 s",t.tower&&t.cursed&&t.cdHeld>4&&t.chains,JSON.stringify(t));
const k=await page.evaluate(()=>{ const d=window.__dd, J=window.__jars; J.clear(); const e=d.enemies.find(x=>x.kind==='archhag'&&!x.dead); d.kill(e); d.step(1/60,5);
  const leg=J.list().filter(j=>j.r===3).length; const sleepers=window.__archhag.asleep(), onField=d.enemies.filter(x=>x.topi&&!x.dead).length;
  for(let i=0;i<180;i++) d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; const bodyAt3s=d.enemies.includes(e); for(let i=0;i<60*40&&d.enemies.includes(e);i++){ d.step(1/60,1); d.S.crystal=d.S.crystal2=1e6; } const bodyAt9s=d.enemies.includes(e);   /* waits (a boss kill may drop a named mythic, whose picture card pauses the hall a while) */ const deadAt9s=+(+e.dead).toFixed(2), holdAt9s=e.deathHold===undefined?null:+e.deathHold.toFixed(2);
  return { leg, sleepers, onField, bodyAt3s, bodyAt9s, deadAt9s, holdAt9s, phase:d.status().phase }; });
check("killing her: 30 Legendary jars burst out, every hopping topiary falls asleep as a statue (none left on the field), her body stays for her fall (still there 3 s on), then goes",k.leg===30&&k.sleepers>=1&&k.onField===0&&k.bodyAt3s&&!k.bodyAt9s,JSON.stringify(k));
const mu=await page.evaluate(()=>window.__mus?window.__mus.state():null);
check("build 310 (Matt: all goes quiet when she comes on and just this solitary drumline): her drumline is a track of its own, fetched with her model",!!mu&&mu.tracks.includes("archhag")&&mu.fetched.includes("archhag"),JSON.stringify(mu&&{tracks:mu.tracks,fetched:mu.fetched}));
const realErrors=errors.filter(e=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(e)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
