import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8906);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const ctx=await browser.newContext({viewport:{width:1100,height:700}}); const page=await ctx.newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error") errors.push(m.text().slice(0,200)); });
await page.goto("http://127.0.0.1:8906/?silent"); await page.waitForFunction(()=>window.__dd&&window.__armory&&window.__doll&&window.__room&&window.__weapons&&window.__dd.heroModel()&&/Meshy/.test(window.__dd.heroModel().label),null,{timeout:120000});
// 1. the training ground (map one) has no level gate since build 137: a wave-7 legendary equips at level 1 there
const r1b=await page.evaluate(()=>{ const d=window.__dd, M=window.__meta; M.reset(); d.resetGear(); const leg=d.rollItem(4,"weapon",7); leg.rarity=4; leg.req=M.reqFor(leg); M.giveItem(leg); const lvl=M.level(); const eq=M.equip(leg.id); return {map:d.map().id,req:leg.req,lvl,eq,worn:!!(d.gear().weapon&&d.gear().weapon.id===leg.id)}; });
check("map one (the training ground) has no level gate: a wave-7 legendary that asks for level 6 equips at level 1",r1b.map==="hall"&&r1b.req===6&&r1b.lvl===1&&r1b.eq===true&&r1b.worn,JSON.stringify(r1b));
// 2. the armory store: stash, unstash, the cap, its own save, reset
const r2=await page.evaluate(()=>{ const d=window.__dd, M=window.__meta; M.reset(); d.resetGear(); const items=[]; for(let i=0;i<10;i++){ const it=d.rollItem(1,["armor","weapon","charm","amulet","familiar"][i%5],4); M.giveItem(it); items.push(it); } const bag0=M.bag().length; let ok=0; for(const it of items) if(M.stash(it.id)) ok++; const arm=M.armory().length, bag1=M.bag().length; const saved=JSON.parse(localStorage.getItem("ddArmory")).length; const back=M.unstash(items[0].id); const arm2=M.armory().length, bag2=M.bag().length; const stands=window.__armory.stands(); const shown=stands.filter(s=>s.shown).length, kinds=stands.map(s=>s.slot); M.reset(); const afterReset=M.armory().length, savedAfter=JSON.parse(localStorage.getItem("ddArmory")).length, standsAfter=window.__armory.stands().filter(s=>s.shown).length; return {bag0,ok,arm,bag1,saved,back,arm2,bag2,shown,kinds,afterReset,savedAfter,standsAfter}; });
check("ten pieces in the bag: eight go on the stands and the ninth is refused; the armory saves on its own (ddArmory); TAKE BACK returns one to the bag; the eight stands show what they hold (one per slot kind); reset empties it all",r2.bag0===10&&r2.ok===8&&r2.arm===8&&r2.bag1===2&&r2.saved===8&&r2.back&&r2.arm2===7&&r2.bag2===3&&r2.shown===7&&r2.kinds.filter(Boolean).length===7&&r2.afterReset===0&&r2.savedAfter===0&&r2.standsAfter===0,JSON.stringify(r2));
// 3. the tavern's armory station prompts and E opens the sheet on the kept piece (map one: the tavern room is here)
const r3b=await page.evaluate(async()=>{ const d=window.__dd, M=window.__meta; M.reset(); d.resetGear(); d.start(); d.step(1/60,3); const plain=d.rollItem(0,"charm",2); M.giveItem(plain);
  M.stash(plain.id); const st=window.__room.stations().find(s=>s.tab==="armory"); d.setHero(st.x,st.z+.4,0); d.step(1/60,3); const prompt=document.getElementById("prompt").textContent; window.dispatchEvent(new KeyboardEvent("keydown",{code:"KeyE",bubbles:true})); await new Promise(r=>setTimeout(r,120)); const opened=window.__doll.isOpen(), sel=window.__doll.selected(); window.__doll.close(); return {prompt,opened,sel}; });
check("the tavern's armory station prompts and E opens the sheet on the kept piece",/armory/.test(r3b.prompt)&&r3b.opened&&r3b.sel&&r3b.sel.from==="arm",JSON.stringify(r3b));
// 4. a look at the stands
await page.evaluate(async()=>{ const d=window.__dd, M=window.__meta; M.reset(); d.resetGear(); if(window.__pause&&window.__pause.isOpen()) window.__pause.close(); for(const [r,s] of [[3,"armor"],[4,"weapon"],[2,"charm"],[3,"amulet"],[1,"familiar"],[2,"armor"]]){ const it=d.rollItem(r,s,6); it.rarity=r; M.giveItem(it); M.stash(it.id); } await new Promise(r=>setTimeout(r,1500)); const c=window.__armory.center(); d.setHero(c[0],c[1]+4.2,Math.PI); d.setCam(Math.PI,.3,6); d.step(1/60,30); document.getElementById("hud").style.display="none"; window.__freeze=true; });
await page.waitForTimeout(300); await page.screenshot({path:SP+"/parts/shots/armory.png"});
// 5. a later map keeps the gate (96-armory.js): the formula is lvl*0.3 + rarity (was 0.8, which locked out nearly everything), and
// the sheet marks a piece above your level, says so on its card, and offers the armory for it
await page.evaluate(()=>{ try{ localStorage.setItem("ddMapsCleared","1"); }catch(e){} });
await page.goto("http://127.0.0.1:8906/?silent&map=1"); await page.waitForFunction(()=>window.__dd&&window.__doll&&window.__meta&&window.__meta.reqFor,null,{timeout:120000});
const r1=await page.evaluate(()=>{ const d=window.__dd, M=window.__meta; M.reset(); d.resetGear(); const roll=(r,s,l)=>{ let it; for(let i=0;i<60;i++){ it=d.rollItem(r,s,l); if(!/ of the (Forest|Void)$/.test(it.name||"")) break; } return it; };   /* a later map's roll can come out a set piece (a Forest one about 1 in 4 on map two), and set pieces ask for level 1 -- the gate is tested on plain gear */ const leg=roll(4,"weapon",7); leg.rarity=4; leg.req=M.reqFor(leg); const com=roll(0,"armor",7); com.rarity=0; com.req=M.reqFor(com); const easy=roll(0,"armor",1); easy.rarity=0; easy.req=M.reqFor(easy); const legacy={slot:"charm",rarity:2,lvl:5,name:"Old Charm",stats:{tow:3},value:10}; M.giveItem(legacy); const legacyReq=M.bag().find(b=>b.name==="Old Charm").req;
  M.giveItem(leg); M.giveItem(com); M.giveItem(easy); const lvl0=M.level(); const eqNo=M.equip(leg.id); const stillBagged=!!M.bag().find(b=>b.id===leg.id); const eqCom=M.equip(com.id); const eqEasy=M.equip(easy.id); M.addXP(40000); const lvl1=M.level(); const eqYes=M.equip(leg.id); return {map:d.map().id,legReq:leg.req,comReq:com.req,easyReq:easy.req,legacyReq,lvl0,eqNo,stillBagged,eqCom,eqEasy,lvl1,eqYes,worn:d.gear().weapon&&d.gear().weapon.id===leg.id}; });
check("map two: a wave-7 legendary asks for level 6 (7×0.3+4), a wave-7 common level 2, a wave-1 common level 1, an old piece without one gets it on load (5×0.3+2 → 4); at level 1 the legendary and the wave-7 common refuse (they stay in the bag) while the wave-1 common equips; after leveling up the legendary equips",r1.map!=="hall"&&r1.legReq===6&&r1.comReq===2&&r1.easyReq===1&&r1.legacyReq===4&&r1.lvl0===1&&!r1.eqNo&&r1.stillBagged&&!r1.eqCom&&r1.eqEasy&&r1.lvl1>=6&&r1.eqYes&&r1.worn,JSON.stringify(r1));
const r3=await page.evaluate(async()=>{ const d=window.__dd, M=window.__meta; M.reset(); d.resetGear(); const roll=(r,s,l)=>{ let it; for(let i=0;i<60;i++){ it=d.rollItem(r,s,l); if(!/ of the (Forest|Void)$/.test(it.name||"")) break; } return it; };   /* a later map's roll can come out a set piece (a Forest one about 1 in 4 on map two), and set pieces ask for level 1 -- the gate is tested on plain gear */ d.start(); d.step(1/60,3); const leg=roll(4,"weapon",7); leg.rarity=4; leg.req=M.reqFor(leg); M.giveItem(leg); const plain=roll(0,"charm",2); M.giveItem(plain); window.__doll.open(); await new Promise(r=>setTimeout(r,300)); let html=window.__doll.html(); const locked=new RegExp('data-id="'+leg.id+'"[^>]*class="[^"]*lock').test(html)||new RegExp('class="inv-c has r4 lock"[^>]*data-id="'+leg.id+'"').test(html); window.__doll.select(leg.id,"bag"); await new Promise(r=>setTimeout(r,300)); html=window.__doll.html(); const needBtn=/level 6 needed/i.test(html), keepBtn=/data-act="stash"/.test(html), armGrid=(html.match(/inv-c stand/g)||[]).length===8;
  document.querySelector('#doll [data-act="stash"]').click(); await new Promise(r=>setTimeout(r,300)); html=window.__doll.html(); const kept=M.armory().length===1&&/TAKE BACK/.test(html)&&/armory · 1 \/ 8/.test(html); document.querySelector('#doll [data-act="unstash"]').click(); await new Promise(r=>setTimeout(r,300)); const took=M.armory().length===0&&M.bag().length===2; window.__doll.close(); return {locked,needBtn,keepBtn,armGrid,kept,took}; });
check("sheet on map two: a piece above your level is marked locked in the grid, its card says LEVEL 6 NEEDED and offers KEEP IN ARMORY; keeping it fills a stand (armory 1/8, TAKE BACK), taking it back empties it",r3.locked&&r3.needBtn&&r3.keepBtn&&r3.armGrid&&r3.kept&&r3.took,JSON.stringify(r3));
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e));
check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
