// ===== THE CART TEAMS (95i-carts.js, build 359). Matt: real orcs push the Blight Keg Cart and the Rammed Iron Fire Cart (Bob's animated models). Checked: a team is the cart and two real orcs standing at its handles, the
// cart rolling and the orcs keeping their places; the cart's pace follows its crew (two orcs full, one half, none it stops and its wheels stop); the keg cart blows up on the Heartroot (the blight blast and cloud) and when it
// is shot dead, freeing its orcs; the fire cart's green jet hurts what it aims at, and it rams with its Ram clip when right up against it; no page errors.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8999,{dist:process.env.DIST||"./dist"});
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const errors=[]; const warns=[];
const ctx=await browser.newContext({viewport:{width:900,height:560}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==='warning'&&/cart|keg|blast/i.test(m.text())) warns.push(m.text().slice(0,160)); });
await page.goto("http://127.0.0.1:8999/?silent&nogate&map=0",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__carts&&window.__blight,null,{timeout:120000});
await page.evaluate(async()=>{ try{ window.__trainer.skip(); }catch(e){} const d=window.__dd; d.start(); d.step(1/60,5); await Promise.all(window.__carts.kinds.map(k=>window.__carts.load(k))); d.setHero(-10,10,0); });
const clear=()=>{ const d=window.__dd; for(const e of d.enemies) if(!e.dead){ e.dead=.001; } };
const T=await page.evaluate(()=>{ const d=window.__dd; d.S.phase='wave'; d.S.crystal=1e6; const n0=d.enemies.length; d.spawn('kegcart','N'); const cart=d.enemies.find(e=>e.kind==='kegcart'); const crew=d.enemies.filter(e=>e.pushFor===cart);
  const x0=cart.x, z0=cart.z; for(let i=0;i<180;i++){ d.step(1/60,1); d.S.crystal=1e6; } const dist=crew.map(o=>+Math.hypot(o.x-cart.x,o.z-cart.z).toFixed(2));
  return { total:d.enemies.length-n0, crew:crew.length, isOrc:crew.every(o=>o.kind==='orc'), moved:+Math.hypot(cart.x-x0,cart.z-z0).toFixed(2), dist, tsMoving:cart.mdl.mixer.timeScale, spd:cart.spd, spd0:cart.spd0 }; });
check("a team is the keg cart and two REAL orcs, standing at its handles (about 3 behind it) while the cart rolls and its wheels turn",T.total===3&&T.crew===2&&T.isOrc&&T.moved>1&&T.dist.every(v=>v>2.6&&v<3.5)&&T.tsMoving===1,JSON.stringify(T));
const S2=await page.evaluate(()=>{ const d=window.__dd; const cart=d.enemies.find(e=>e.kind==='kegcart'&&!e.dead); const crew=cart.crew; const full=cart.spd; d.kill(crew[0]); for(let i=0;i<10;i++){ d.step(1/60,1); d.S.crystal=1e6; } const half=cart.spd; d.kill(crew[1]); for(let i=0;i<30;i++){ d.step(1/60,1); d.S.crystal=1e6; } const none=cart.spd; const p0=[cart.x,cart.z]; for(let i=0;i<60;i++){ d.step(1/60,1); d.S.crystal=1e6; } return { full, half, none, still:Math.hypot(cart.x-p0[0],cart.z-p0[1]), ts:cart.mdl.mixer.timeScale, alive:!cart.dead }; });
check("the cart's pace follows its crew: two orcs full pace, one half, none it stops dead and its wheels stop turning (and it stays a live bomb)",S2.half>S2.full*.4&&S2.half<S2.full*.6&&S2.none===0&&S2.still<.9&&S2.ts===0&&S2.alive,JSON.stringify(S2));
const K=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) if(!e.dead){ e.dead=.001; } d.S.crystal=300; const c0=window.__blight.info().cloudsMade; d.spawn('kegcart','N'); const cart=d.enemies.filter(e=>e.kind==='kegcart'&&!e.dead).pop(); cart.spd0=0; cart.x=0; cart.z=-1.6; const crew=cart.crew; crew.forEach(o=>{ o.hp=o.max=1e6; });
  for(let i=0;i<240&&!cart.dead;i++){ d.step(1/60,1); } return { dead:!!cart.dead, crystalHurt:d.S.crystal<300, clouds:window.__blight.info().cloudsMade-c0, blasts:window.__carts.info().blasts, crewHurt:crew.some(o=>o.hp<o.max), crewFreed:crew.every(o=>o.pushFor===null&&o.spd===o.spd0&&o.spd>0) }; });
check("the keg cart blows up on the Heartroot: the blight blast and cloud go off, the crystal is hurt, the pushers are caught in it and then freed to fight on as plain orcs",K.dead&&K.crystalHurt&&K.clouds===1&&K.blasts===1&&K.crewHurt&&K.crewFreed,JSON.stringify(K));
const Sh=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) if(!e.dead){ e.dead=.001; } d.S.crystal=1e6; const c0=window.__blight.info().cloudsMade, b0=window.__carts.info().blasts; d.spawn('kegcart','N'); const cart=d.enemies.filter(e=>e.kind==='kegcart'&&!e.dead).pop(); d.kill(cart); return { clouds:window.__blight.info().cloudsMade-c0, blasts:window.__carts.info().blasts-b0 }; });
check("a keg cart shot dead goes up once (one blast, one cloud)",Sh.clouds===1&&Sh.blasts===1,JSON.stringify(Sh));
const F=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) if(!e.dead){ e.dead=.001; } d.S.crystal=300; d.S.mana=9999; d.S.du=0; const tw=d.placeDefAt('harpoon',6,-6,0); tw.hp=tw.max=5000; d.spawn('firecart','N'); const cart=d.enemies.filter(e=>e.kind==='firecart'&&!e.dead).pop(); cart.spd0=0; cart.x=6; cart.z=-11.5; cart.crew.forEach(o=>{ o.hp=o.max=1e6; }); const hp0=tw.hp; const played=new Set();
  for(let i=0;i<60*5;i++){ d.step(1/60,1); d.S.crystal=300; const cn=cart.mdl.cur&&cart.mdl.cur.getClip().name; if(cn) played.add(cn); } return { towerHurt:tw.hp<hp0, flames:window.__carts.info().flames, clips:[...played] }; });
check("the fire cart spits its green jet at a tower in range (the tower is hurt, the Fire clip plays)",F.towerHurt&&F.flames>0&&F.clips.includes('Fire'),JSON.stringify(F));
const Rm=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) if(!e.dead){ e.dead=.001; } d.S.crystal=300; d.spawn('firecart','N'); const cart=d.enemies.filter(e=>e.kind==='firecart'&&!e.dead).pop(); cart.spd0=0; cart.x=0; cart.z=-3.2; cart.crew.forEach(o=>{ o.hp=o.max=1e6; }); const r0=window.__carts.info().rams; const played=new Set(); let minC=300; for(let i=0;i<60*6;i++){ d.step(1/60,1); minC=Math.min(minC,d.S.crystal); const cn=cart.mdl.cur&&cart.mdl.cur.getClip().name; if(cn) played.add(cn); } return { rams:window.__carts.info().rams-r0, clips:[...played], crystalHurt:minC<300 }; });
check("right up against the Heartroot the fire cart RAMS (its Ram clip, a blow half as hard again) rather than spitting",Rm.rams>0&&Rm.clips.includes('Ram')&&Rm.crystalHurt,JSON.stringify(Rm));
check("no model failed to load",warns.length===0,warns.slice(0,3).join(' | '));
const realErrors=errors.filter(x=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(x)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
