import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8873);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const ctx=await browser.newContext({viewport:{width:1100,height:700}}); const page=await ctx.newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error"||m.type()==="warning") errors.push(m.text().slice(0,200)); });
await page.goto("http://127.0.0.1:8873/?silent&nogate"); await page.waitForFunction(()=>window.__dd&&window.__heroes&&window.__weapons&&window.__dd.heroModel()&&/Meshy/.test(window.__dd.heroModel().label),null,{timeout:120000});   /* a fresh player is the knight since build 134; any hero model landing is the signal */
const r0=await page.evaluate(()=>({pick:window.__heroes.pick(),line:document.getElementById("heroline").textContent,reach:window.__dd.hero.reach}));
check("a fresh player is the Gnome Knight (the other heroes unlock once map one is held), reach 2.4",r0.pick==="knight"&&/GNOME KNIGHT/.test(r0.line)&&r0.reach===2.4,JSON.stringify(r0));
// clips present, a staff (not a sword) in her left hand, reach 18, and a swing throws a bolt that hits a goblin 8 units out
await page.evaluate(()=>window.__heroes.select('witch')); await page.waitForFunction(()=>/Witch/.test(window.__dd.heroModel().label),null,{timeout:120000});   /* a fresh player is the knight since build 134: pick the witch for her section */
const r1=await page.evaluate(async()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.step(1/60,5); const m=d.heroModel(); const e=d.spawn("goblin","N"); d.setHero(0,10,0); d.setCam(0,.3,6); d.step(1/60,3); e.x=0; e.z=18; e.spd=0; const hp0=e.hp; let ws0=window.__weapons.state(); for(let i=0;i<200&&!(ws0.mounted&&ws0.staff);i++){ d.step(1/60,1); ws0=window.__weapons.state(); await new Promise(r=>setTimeout(r,30)); } d.swing(); let bolts=0, hitAt=-1; const clips=[]; for(let i=0;i<90;i++){ d.step(1/60,1); e.x=0; e.z=18; bolts=Math.max(bolts,window.__staff.bolts()); clips.push(d.heroModel().cur); if(hitAt<0&&e.hp<hp0) hitAt=i; } const hit=e.hp<hp0; d.kill(e); d.step(1/60,40); const ws=window.__weapons.state(); const V=window.__void; const vit=d.rollItem(3,"weapon",8); V.make(vit); const voidStaff=window.__staff.staffFor(vit); const t1=window.__staff.staffFor({name:"Rusty Shortsword",rarity:0,tier:1}), t5=window.__staff.staffFor({name:"Kingsguard Greatsword",rarity:4,tier:5});
  return {label:m.label,clips:m.clips,reach:d.hero.reach,hit,hitAt,bolts,mounted:ws.mounted,staff:ws.staff,whip:ws.whip,key:ws.key,mount:ws.mount,clipPlayed:clips.some(c=>c==='Attack'),voidStaff,t1,t5,pick:window.__heroes.pick(),saved:localStorage.getItem("ddHero"),line:document.getElementById("heroline").textContent}; });
check("witch: all six clips, reach 18, a staff is mounted in her left hand (no sword, no whip), her staff-thrust clip plays on a swing and the bolt it throws hits a goblin 8 units ahead within a second, and the staff set is mapped (tier 1 → hazel, tier 5 → battle, a Void item → the Staff of the Void)",/Witch/.test(r1.label)&&["idle","walk","run","attack","jump","death"].every(c=>r1.clips.includes(c))&&r1.reach===18&&r1.hit&&r1.hitAt>=0&&r1.hitAt<60&&r1.bolts>0&&r1.mounted&&r1.staff&&!r1.whip&&/^staff-/.test(r1.key)&&r1.mount&&r1.mount.bone==="LeftHand"&&r1.mount.staff&&r1.clipPlayed&&r1.voidStaff==="staff-void"&&r1.t1==="staff-hazel"&&r1.t5==="staff-battle"&&r1.pick==="witch"&&r1.saved==="witch"&&/GNOME BATTLE WITCH/.test(r1.line),JSON.stringify(r1));
// the troll archer: a bow in the left hand, reach 24, and a swing looses an arrow that hits a goblin 10 units out
await page.evaluate(()=>window.__heroes.select("troll")); await page.waitForFunction(()=>/Troll/.test(window.__dd.heroModel().label),null,{timeout:90000});
const rt=await page.evaluate(async()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.step(1/60,5); const m=d.heroModel(); let ws0=window.__weapons.state(); for(let i=0;i<200&&!(ws0.mounted&&ws0.bow);i++){ d.step(1/60,1); ws0=window.__weapons.state(); await new Promise(r=>setTimeout(r,30)); } const e=d.spawn("goblin","N"); d.setHero(0,10,0); d.setCam(0,.3,6); d.step(1/60,3); e.x=0; e.z=20; e.spd=0; const hp0=e.hp; d.swing(); let arrows=0, hitAt=-1; const clips=[]; for(let i=0;i<90;i++){ d.step(1/60,1); e.x=0; e.z=20; arrows=Math.max(arrows,window.__bow.arrows()); clips.push(d.heroModel().cur); if(hitAt<0&&e.hp<hp0) hitAt=i; } const hit=e.hp<hp0; d.kill(e); d.step(1/60,40); const ws=window.__weapons.state(); const V=window.__void; const vit=d.rollItem(3,"weapon",8); V.make(vit);
  return {label:m.label,clips:m.clips,reach:d.hero.reach,hit,hitAt,arrows,mounted:ws.mounted,bow:ws.bow,staff:ws.staff,key:ws.key,mount:ws.mount,clipPlayed:clips.some(c=>c==='Attack'),voidBow:window.__bow.bowFor(vit),t1:window.__bow.bowFor({name:"x",tier:1}),t5:window.__bow.bowFor({name:"x",tier:5}),pick:window.__heroes.pick(),line:document.getElementById("heroline").textContent}; });
check("troll archer: all six clips, reach 24, a bow (not a staff or sword) mounted in his left hand, the archery clip plays on a swing and its arrow hits a goblin 10 units ahead within a second; bows map by tier (1 → ash, 5 → war) and the Void set to the Bow of the Void",/Troll/.test(rt.label)&&["idle","walk","run","attack","jump","death"].every(c=>rt.clips.includes(c))&&rt.reach===24&&rt.hit&&rt.hitAt>=0&&rt.hitAt<60&&rt.arrows>0&&rt.mounted&&rt.bow&&!rt.staff&&/^bow-/.test(rt.key)&&rt.mount&&rt.mount.bone==="LeftHand"&&rt.mount.bow&&rt.clipPlayed&&rt.voidBow==="bow-void"&&rt.t1==="bow-ash"&&rt.t5==="bow-war"&&rt.pick==="troll",JSON.stringify(rt));
// the gnome knight: a sword in the right hand, reach 2.4, and a swing hits a goblin in melee range
await page.evaluate(()=>window.__heroes.select("knight")); await page.waitForFunction(()=>/Knight/.test(window.__dd.heroModel().label),null,{timeout:90000});
const rk=await page.evaluate(async()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.step(1/60,5); const m=d.heroModel(); let ws0=window.__weapons.state(); for(let i=0;i<200&&!(ws0.mounted&&!ws0.staff&&!ws0.bow);i++){ d.step(1/60,1); ws0=window.__weapons.state(); await new Promise(r=>setTimeout(r,30)); } const e=d.spawn("goblin","N"); d.setHero(0,10,0); d.setCam(0,.3,6); d.step(1/60,3); e.x=0; e.z=11.5; e.spd=0; const hp0=e.hp; d.swing(); let hitAt=-1; const clips=[]; for(let i=0;i<90;i++){ d.step(1/60,1); e.x=0; e.z=11.5; clips.push(d.heroModel().cur); if(hitAt<0&&e.hp<hp0) hitAt=i; } const hit=e.hp<hp0; d.kill(e); d.step(1/60,40); const ws=window.__weapons.state(); const t1=window.__weapons.swordFor({name:"Rusty Shortsword",rarity:0,tier:1});
  return {label:m.label,clips:m.clips,reach:d.hero.reach,hit,hitAt,mounted:ws.mounted,staff:ws.staff,bow:ws.bow,key:ws.key,mount:ws.mount,clipPlayed:clips.some(c=>c==='Attack'),t1,pick:window.__heroes.pick()}; });
check("gnome knight: all six clips, reach 2.4, a sword (not a staff or bow) mounted in his right hand, the slash clip plays on a swing and hits a goblin in melee range",/Knight/.test(rk.label)&&["idle","walk","run","attack","jump","death"].every(c=>rk.clips.includes(c))&&rk.reach===2.4&&rk.hit&&rk.hitAt>=0&&rk.hitAt<60&&rk.mounted&&!rk.staff&&!rk.bow&&rk.mount&&rk.mount.bone==="RightHand"&&!rk.mount.staff&&!rk.mount.bow&&rk.clipPlayed&&/^rusty\|/.test(rk.key)&&rk.t1==="rusty"&&rk.pick==="knight",JSON.stringify(rk));
// the gnome fighter: a staff (not a sword or bow) in his left hand too, reach 18, and a swing throws a bolt that hits a goblin 8 units out
await page.evaluate(()=>window.__heroes.select("fighter")); await page.waitForFunction(()=>/Fighter/.test(window.__dd.heroModel().label),null,{timeout:90000});
const rf=await page.evaluate(async()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.step(1/60,5); const m=d.heroModel(); const e=d.spawn("goblin","N"); d.setHero(0,10,0); d.setCam(0,.3,6); d.step(1/60,3); e.x=0; e.z=18; e.spd=0; const hp0=e.hp; let ws0=window.__weapons.state(); for(let i=0;i<200&&!(ws0.mounted&&ws0.staff);i++){ d.step(1/60,1); ws0=window.__weapons.state(); await new Promise(r=>setTimeout(r,30)); } d.swing(); let bolts=0, hitAt=-1; const clips=[]; for(let i=0;i<90;i++){ d.step(1/60,1); e.x=0; e.z=18; bolts=Math.max(bolts,window.__staff.bolts()); clips.push(d.heroModel().cur); if(hitAt<0&&e.hp<hp0) hitAt=i; } const hit=e.hp<hp0; d.kill(e); d.step(1/60,40); const ws=window.__weapons.state();
  return {label:m.label,clips:m.clips,reach:d.hero.reach,hit,hitAt,bolts,mounted:ws.mounted,staff:ws.staff,bow:ws.bow,key:ws.key,mount:ws.mount,clipPlayed:clips.some(c=>c==='Attack'),pick:window.__heroes.pick(),unlocks:window.__heroes.unlocks()}; });
check("gnome fighter: all six clips, reach 18, a staff (not a sword or bow) mounted in his left hand, his cast clip plays on a swing and the bolt it throws hits a goblin 8 units ahead within a second, and he unlocks zap/ember/dazzle",/Fighter/.test(rf.label)&&["idle","walk","run","attack","jump","death"].every(c=>rf.clips.includes(c))&&rf.reach===18&&rf.hit&&rf.hitAt>=0&&rf.hitAt<60&&rf.bolts>0&&rf.mounted&&rf.staff&&!rf.bow&&/^staff-/.test(rf.key)&&rf.mount&&rf.mount.bone==="LeftHand"&&rf.mount.staff&&rf.clipPlayed&&rf.pick==="fighter"&&rf.unlocks.join()==="zap,ember,dazzle",JSON.stringify(rf));
// and back to the witch: her staff returns
await page.evaluate(()=>window.__heroes.select("witch")); await page.waitForFunction(()=>/Witch/.test(window.__dd.heroModel().label),null,{timeout:90000});
const r2=await page.evaluate(async()=>{ const d=window.__dd; for(let i=0;i<150;i++){ d.step(1/60,1); const st=window.__weapons.state(); if(st.mounted&&st.staff) break; await new Promise(r=>setTimeout(r,40)); } return {reach:d.hero.reach,staff:window.__weapons.state().mounted&&window.__weapons.state().staff,mount:window.__weapons.state().mount}; });
check("witch again: reach 18 and the staff is back in hand (a staff mount, not a bow mount)",r2.reach===18&&r2.staff&&r2.mount&&r2.mount.staff,JSON.stringify(r2));
// test shortcuts: auto-mana pulls orbs from across the hall; unlock all maps opens map 2; +1000 gold
const r3=await page.evaluate(async()=>{ const d=window.__dd; const g0=window.__meta.gold(); document.querySelector('#testline [data-t="gold"]').click(); const gold=window.__meta.gold()-g0; document.querySelector('#testline [data-t="mana"]').click(); const on=window.__autoMana; d.setHero(0,10,0); for(let i=0;i<5;i++){ const e=d.spawn("goblin","N"); e.x=0; e.z=-20; d.kill(e); } d.step(1/60,2); const orbs0=d.orbs.length; const m0=d.S.mana; for(let i=0;i<60*8&&d.orbs.length;i++) d.step(1/60,1); const got=d.S.mana-m0; document.querySelector('#testline [data-t="maps"]').click(); const line=document.getElementById("mapline").textContent, test=document.getElementById("testline").textContent, cleared=localStorage.getItem("ddMapsCleared"); const wipeBtn=document.querySelector('#testline [data-t="wipe"]'); wipeBtn.click(); const armed=/click again/.test(wipeBtn.textContent); localStorage.setItem("ddProbe","1"); window.__fresh.wipe(); const wiped=localStorage.getItem("ddProbe")===null&&localStorage.getItem("ddMapsCleared")===null; return {gold,on,orbs0,left:d.orbs.length,got,cleared,line,test,hasReload:!!document.querySelector('#testline [data-t="reload"]'),armed,wiped}; });
check("testing panel: +1000 gold, auto-mana drags orbs from 30 units away, unlock-all marks every map cleared; a fresh-reload button, and wipe saves arms on the first click and forgets every dd* key",r3.gold===1000&&r3.on&&r3.orbs0>0&&r3.left===0&&r3.got>0&&r3.cleared==="5"&&/✓/.test(r3.line)&&/unlocked ✓/.test(r3.test)&&r3.hasReload&&r3.armed&&r3.wiped,JSON.stringify(r3));
await page.evaluate(()=>window.__campaign.unlockAll()); await page.goto("http://127.0.0.1:8873/?silent&nogate&map=1"); await page.waitForFunction(()=>window.__dd&&window.__dd.map,null,{timeout:90000});
const r4=await page.evaluate(()=>window.__dd.map().index);
check("after unlock-all, ?map=1 opens the throne room",r4===1,String(r4));
// screenshots: the witch on the throne room's lower floor, then her bolt in flight at a goblin up the middle stair
await page.evaluate(async()=>{ window.__heroes.select("witch"); await new Promise(r=>setTimeout(r,2500)); const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); for(let i=0;i<120;i++){ d.step(1/60,1); const st=window.__weapons.state(); if(st.mounted&&st.staff) break; await new Promise(r=>setTimeout(r,30)); } d.setHero(0,60,Math.PI); d.hero.y=0; d.setCam(Math.PI-.7,.2,4.2); d.step(1/60,20); document.getElementById("hud").style.display="none"; });
await page.waitForTimeout(200); await page.screenshot({path:SP+"/parts/shots/witch.png",timeout:120000});
await page.evaluate(()=>{ const d=window.__dd; const e=d.spawn("goblin","S"); d.step(1/60,2); e.x=0; e.z=51; e.spd=0; d.setHero(0,60,Math.PI); d.hero.y=0; d.setCam(Math.PI-.9,.16,5.5); d.step(1/60,10); d.swing(); for(let i=0;i<40;i++){ d.step(1/60,1); e.x=0; e.z=51; if(window.__staff.bolts()) break; } d.step(1/60,5); e.x=0; e.z=51; });
await page.waitForTimeout(150); await page.screenshot({path:SP+"/parts/shots/witch-bolt.png",timeout:120000});
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e));
check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
