// ===== THE EASED SLUDGE ECONOMY (hideout build 56). Matt: "i am finding that i am not making enough sludge per round, 5 maybe too many on some of the sludge jars", "my barometer is that i should be able to do the loot gamble 2-3 times per
// round". A forge try costs 3 Legendary Sludge (was 5), every Refine step takes 3 of a sludge for one of the next (was 5), salvage stays 2 pieces to 1. Checked on the real recipe table and the real buttons.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8904);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const errors=[];
const ctx=await browser.newContext({viewport:{width:1280,height:800}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddSound","off"); localStorage.setItem("ddMapsCleared","1"); }catch(e){} });
const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e)));
await page.goto("http://127.0.0.1:8904/?silent&nogate",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__hideout,null,{timeout:120000});
await page.evaluate(()=>{ window.__dd.start(); window.__dd.step(1/60,10); window.__dd.setHero(30,30); window.__hideout.open(); }); let f=null; for(let i=0;i<600&&!f;i++){ f=page.frames().find(x=>x.url().includes("hideout/index.html")); if(!f) await sleep(50); }
await f.waitForFunction(()=>typeof RECIPES!=="undefined"&&typeof openCauldron==="function"&&typeof openForge==="function",null,{timeout:120000});
const a=await f.evaluate(()=>{ openCauldron(); const label=[...document.querySelectorAll(".csection")].map(e=>e.textContent); return { forge:FORGE_COST, refine:RECIPES.filter(r=>r.kind==="refine").map(r=>r.cost), salvage:RECIPES.filter(r=>r.kind==="salvage").map(r=>r.cost), label }; });
check("a forge craft costs 6 (hideout 88: the crafting forge, it always makes the piece), every Refine step takes 3, salvage is still 2 pieces (1 for a legendary piece), and the cart says 'three'",a.forge===6&&a.refine.join()==="3,3,3"&&a.salvage.join()==="2,2,2,2,1"&&a.label.some(t=>/Refine — three of a sludge/.test(t)),JSON.stringify(a));
const b=await f.evaluate(()=>{ SAVE.commonSludge=3; SAVE.uncommonSludge=6; SAVE.sludge=3; SAVE.legendarySludge=0; craftRecipe("rf_uncommon",false); craftRecipe("rf_rare",false); craftRecipe("rf_rare",false); craftRecipe("rf_legendary",false); return { common:SAVE.commonSludge, uncommon:SAVE.uncommonSludge, rare:SAVE.sludge, legendary:SAVE.legendarySludge }; });
check("three Common Sludge refine to one Uncommon; three Uncommon to one Rare; three Rare to one Legendary (uncommon 6+1 -> 4 -> 1, rare 3+2 -> 5 -> 2 after one legendary)",b.common===0&&b.uncommon===1&&b.rare===2&&b.legendary===1,JSON.stringify(b));
const c=await f.evaluate(async()=>{ closeCauldron&&closeCauldron(); SAVE.legendarySludge=12; window.__forgeFast=true; openForge(); forgeSelected="weapon"; forgeSet="shadow"; forgeFocus="dmg"; buildForgeGrid(); const btn=document.getElementById("forgeCraftBtn"); const t0=btn.textContent; const real=Math.random; Math.random=()=>0.5; try{ btn.click(); await new Promise(r=>setTimeout(r,30)); btn.click(); await new Promise(r=>setTimeout(r,30)); btn.click(); } finally { Math.random=real; } return { t0, left:SAVE.legendarySludge, disabledNow:document.getElementById("forgeCraftBtn").disabled }; });
check("twelve Legendary Sludge is two crafts at 6 each, then the button is off",c.t0==="Craft · 6 sludge"&&c.left===0&&c.disabledNow===true,JSON.stringify(c));
const realErrors=errors.filter(e=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(e)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
