import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const SP=process.env.SP; const server=await serve(8897);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const ctx=await browser.newContext({viewport:{width:1100,height:700}}); const page=await ctx.newPage(); const errors=[]; page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==="error"||m.type()==="warning") errors.push(m.text().slice(0,200)); });
const ready=(room=true)=>page.waitForFunction(room=>window.__dd&&window.__dd.map&&window.__campaign&&window.__dd.heroModel()&&window.__dd.mobModel("goblin")&&window.__dd.mobModel("drake")&&(!room||window.__room),room,{timeout:120000});   // build 379: the Drawbridge has no tavern room now (its inn is closed), so only the first map is waited on for one
await page.goto("http://127.0.0.1:8897/?silent&nogate"); await ready(); await page.evaluate(()=>window.__campaign.unlockAll());
await page.goto("http://127.0.0.1:8897/?silent&nogate&map=4"); await ready(false);
// the map: its grid, roots and mana, and where each gate's stream runs (world x=(cx-20)*2, z=(cz-7)*2: the crystal is cell 20,7)
const r=await page.evaluate(()=>{ const d=window.__dd; window.__meta.reset(); d.resetGear(); d.start(); d.step(1/60,5); const L=d.lanes(), m=d.map(), w=d.worldInfo(), gw=m.gw; const paths=Object.fromEntries(Object.keys(L).map(k=>[k,d.pathLen(L[k].cx,L[k].cz)]));
  const trace=(f,cx,cz)=>{ let i=cz*gw+cx; const cells=[]; for(let n=0;n<600&&i>=0;n++){ cells.push([i%gw,(i/gw)|0]); i=f.nxt[i]; } return cells; }; const onFord=c=>(c[0]===4||c[0]===5)&&c[1]>=24&&c[1]<=27, onBridge=c=>c[0]>=23&&c[0]<=25&&c[1]>=24&&c[1]<=27;   // (build 383: the map is padded 8 rows north, every row below is 8 more)
  const W=trace(d.flow(),1,33), S=trace(d.flow(),24,61), E=trace(d.flow(),48,33), F=trace(d.flowFly(),24,61);
  return {id:m.id,gw:m.gw,gh:m.gh,style:m.style,windows:m.windows,lanes:Object.keys(L),from:Object.fromEntries(Object.keys(L).map(k=>[k,L[k].from])),paths,wFord:W.some(onFord),wBridge:W.some(onBridge),sBridge:S.some(onBridge),eBridge:E.some(onBridge),flyReach:d.flowFly().dist[25*gw+10]>=0,walkReach:d.flow().dist[25*gw+10]>=0,flyLen:F.length,water:w.water,merlons:w.merlons,bridge:w.bridge,duCap:w.duCap,mana:d.S.mana,du:document.getElementById("du").textContent,moat:d.cellAt(10,25),bridgeCell:d.cellAt(24,25),fordCell:d.cellAt(4,25),bed:d.hgtAt(10,25),bank:d.hgtAt(10,28),line:window.__campaign.line()}; });
console.log(JSON.stringify(r));
check("map 5 The Drawbridge: a 50×64 outdoor castle green (padded 8 rows north for the hall roof, build 383) (grass, a paved road, lit windows) with a 172-cell moat sunk below its banks, 220 merlons on the outer walls (build 418: the ward's walls are the wall-walk now, crowned by 56m-moatwalk.js) and a bridge; 90 roots and 520 mana; four gates open in turn (road 1, west wood 2, east wood 3, sally port 5); the road and the east wood cross the drawbridge (paths ≥45 and ≥42), the west wood takes the old ford (≥32, never the bridge), the sally port ≥25; the flyers' field reaches over the water where the walkers' does not",
  r.id==="moat"&&r.gw===50&&r.gh===64&&r.style.outdoor&&r.style.grass&&r.style.road&&r.windows>=0&&r.water===172&&r.merlons===220&&r.bridge&&r.duCap===90&&r.mana===520&&r.du==="0/90"&&r.lanes.join()==="S,W,E,NE"&&r.from.S===1&&r.from.W===2&&r.from.E===3&&r.from.NE===5&&r.paths.S>=45&&r.paths.E>=42&&r.paths.W>=32&&r.paths.NE>=25&&r.sBridge&&r.eBridge&&r.wFord&&!r.wBridge&&r.flyReach&&!r.walkReach&&r.flyLen<=r.paths.S+1&&r.moat===8&&r.bridgeCell===2&&r.fordCell===2&&r.bed<-1&&r.bank===0&&/MAP 5 OF 6/.test(r.line),JSON.stringify(r));
// walkers keep their feet dry, flyers skim the moat: a west goblin takes the causeway, a road drake crosses the water; both reach the crystal
const r2=await page.evaluate(()=>{ const d=window.__dd; const cellOf=e=>[Math.floor((e.x+41)/2),Math.floor((e.z+31)/2)]; const gob=d.spawn("goblin","W"); gob.spd=9; let wet=false, ford=false, okG=false; for(let i=0;i<60*40;i++){ d.step(1/60,1); const [cx,cz]=cellOf(gob); if(d.cellAt(cx,cz)===8) wet=true; if((cx===4||cx===5)&&cz>=24&&cz<=27) ford=true; if(Math.hypot(gob.x,gob.z)<3.6){ okG=true; break; } if(gob.dead) break; } d.kill(gob);
  const dr=d.spawn("drake","S"); dr.spd=9; let okD=false, minY=9; for(let i=0;i<60*40;i++){ d.step(1/60,1); if(i>30) minY=Math.min(minY,dr.y); if(Math.hypot(dr.x,dr.z)<4.2){ okD=true; break; } if(dr.dead) break; } const hp=dr.max; d.kill(dr); d.step(1/60,30); return {wet,ford,okG,okD,minY:+minY.toFixed(2),drakeHp:d.MOBS.drake.hp,drakeMax:hp}; });
check("a west goblin walks the ford dry-shod to the crystal; a road drake flies in through the gate and gets there too, never dipping below the banks; drakes carry 32 hp now, not 70",!r2.wet&&r2.ford&&r2.okG&&r2.okD&&r2.minY>0&&r2.drakeHp===32,JSON.stringify(r2));
// the hero stops at the bank; defenses stand on the bridge and the causeway, never in the water
await page.evaluate(()=>{ const d=window.__dd; d.setHero(-20,26,Math.PI); d.hero.y=0; d.setCam(Math.PI,.2,6); d.step(1/60,5); }); await page.keyboard.down("KeyW"); await page.waitForTimeout(1500); await page.keyboard.up("KeyW");
const r3=await page.evaluate(()=>{ const d=window.__dd; d.step(1/60,5); const z=+d.hero.z.toFixed(2); const onBridge=!!d.place("harpoon",24,25,0), onFord=!!d.place("acorn",4,25,0), inWater=!!d.place("harpoon",10,25,0), onGreen=!!d.place("acorn",30,30,0); return {z,onBridge,onFord,inWater,onGreen,defs:d.defs.length}; });
check("the hero walking north from the bank stays on it (z ≥ 25); a ballista stands on the drawbridge and an acorn cannon on the causeway, nothing in the moat, an acorn cannon on the green",r3.z>=24.9&&r3.onBridge&&r3.onFord&&!r3.inWater&&r3.onGreen&&r3.defs===3,JSON.stringify(r3));

// ---- build 383: the main hall's roof (Matt: "give me stair access to the roof of the main hall, the top will be a defense area") and the inn three more squares north
const RF=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) e.dead=e.dead||.001; d.S.phase='build'; const cw=x=>2*x+1-41, cwz=z=>2*z+1-31; const info=window.__moatroof.info();
  d.setHero(cw(34),cwz(19),Math.PI); d.setCam(Math.PI,.4,8); for(let i=0;i<10;i++) d.step(1/60,1); d.setKeys({w:true}); for(let f=0;f<60*4;f++){ d.cam.yaw=Math.PI; d.step(1/60,1); } d.setKeys({w:false}); const up={ y:+d.hero.y.toFixed(2), z:+d.hero.z.toFixed(1) };
  // walk south toward the front edge, away from the stair: the parapet stops him
  d.setHero(cw(22),cwz(5),0); d.hero.y=8; for(let i=0;i<10;i++) d.step(1/60,1); d.setKeys({s:true}); for(let f=0;f<60*3;f++){ d.cam.yaw=Math.PI; d.step(1/60,1); } d.setKeys({s:false}); const edge={ y:+d.hero.y.toFixed(2), z:+d.hero.z.toFixed(2) };
  d.S.mana=9999; d.S.du=0; const t=d.place('harpoon',20,6,0); const tower=t?{ base:t.base }:null; const gw=d.map().gw;
  return { info, up, edge, tower, roofReach:d.flow().dist[6*gw+26]>=0, inn:[d.cellAt(29,34),d.cellAt(34,34),d.cellAt(30,35),d.cellAt(34,42)], innLow:d.worldInfo().merlons }; });
check("the hall roof: a stair three wide at its east end carries the hero from the ward up to the roof, eight up; the parapet along the front edge stops him walking off (he stays up at 8); a ballista can be set up there, and the horde's road never climbs to it (the stair is too steep for their pathing: up there towers are hit only by shots and bombs); the inn stands three squares further north, closed (build 418: its walls are a paved walk now)",RF.up.y===8&&RF.edge.y===8&&RF.edge.z<-11.5&&RF.tower&&RF.tower.base===8&&!RF.roofReach&&RF.info.boxes===19&&RF.inn[0]===2&&RF.inn[1]===2&&RF.inn[2]===1,JSON.stringify(RF));
// shots: the approach up the royal road, the bridge foot, the ward and the keep, the ford, and a look down from over the wall
const shot=async(name,hx,hz,yaw,pitch,dist)=>{ await page.evaluate(([hx,hz,yaw,pitch,dist])=>{ const d=window.__dd; d.setHero(hx,hz,yaw); d.hero.y=0; d.setCam(yaw,pitch,dist); d.step(1/60,30); document.getElementById("hud").style.display="none"; },[hx,hz,yaw,pitch,dist]); await page.waitForTimeout(250); await page.screenshot({path:SP+"/parts/shots/"+name+".png"}); };
await shot("moat-approach",8,60,Math.PI,.22,9); await shot("moat-bridge",8,26,Math.PI,.18,7); await shot("moat-ward",8,10,0,.28,10); await shot("moat-keep",-4,8,Math.PI,.42,12); await shot("moat-ford",-32,28,Math.PI,.2,8); await shot("moat-above",8,34,Math.PI,.95,34);
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e));
check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
