// ===== THE PRISON'S FLOOR IN MATT'S SIX TILES (56j-prisonfloor.js, build 370). Matt sent the six Meshy floor tiles. Checked: all six load (each a 1,250-triangle height-field slab); every walkable cell is given one of the six (a plain slab
// the commonest, each kind present), the old painted floor plane hidden and the pit given a floor of its own, the terraces' own floor mesh repainted from a 3 x 2 atlas of the six pictures (every uv inside it); the real relief tiles are
// instanced near the camera only (a few hundred triangles' worth, never the whole floor) and follow it; the floor sits just under the old floor level; the hero's feet are still on the floor; no page errors.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8991,{dist:process.env.DIST||"./dist"});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const errors=[]; const warns=[];
const ctx=await browser.newContext({viewport:{width:900,height:560}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==='warning'&&/prison floor/i.test(m.text())) warns.push(m.text().slice(0,160)); });
await page.goto("http://127.0.0.1:8991/?silent&nogate&map=5&floortiles",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__prisonfloor&&window.__prisonfloor.refill&&window.__dd.map().id==='prison',null,{timeout:120000});
await page.evaluate(()=>{ try{ window.__trainer.skip(); }catch(e){} const d=window.__dd; d.start(); d.step(1/60,5); d.S.phase='build'; });
const A=await page.evaluate(()=>{ const F=window.__prisonfloor, i=F.info(), mix=F.mix(); const tot=Object.values(mix).reduce((a,b)=>a+b,0); const d=window.__dd, sc=typeof d.scene==='function'?d.scene():d.scene; const plane=sc.children.find(o=>o.type==='Group'&&o.children.length)&&null; return { tris:i.tris, atlas:i.atlas, kinds:i.kinds, cells:i.cells, tot, mix, plainShare:+(mix[1]/tot).toFixed(2), pit:i.pitCells, far:i.farQuads }; });
check("all six tiles load, each a 1,250-triangle height-field slab, with an atlas of their six pictures",A.kinds===6&&A.atlas===1&&A.tris.length===6&&A.tris.every(t=>t===1250),JSON.stringify({ kinds:A.kinds, tris:A.tris, atlas:A.atlas }));
check("every walkable cell has one of the six (over a thousand cells, laid in 2 x 2 blocks since build 378: a couple of hundred whole-block relief tiles), a plain slab the commonest (about two thirds) and every kind present",A.tot>1000&&A.cells>150&&A.cells<400&&A.plainShare>.58&&A.plainShare<.78&&[1,2,3,4,5,6].every(k=>A.mix[k]>20),JSON.stringify({ cells:A.cells, mix:A.mix, plain:A.plainShare }));
const B=await page.evaluate(()=>{ const d=window.__dd, sc=typeof d.scene==='function'?d.scene():d.scene; const fm=sc.children.find(o=>o.type==='Group'); const world=fm; let floorMesh=null, pit=null, plane=null; world.traverse(o=>{ if(o.isMesh&&o.material&&o.material.map&&o.material.map.image&&o.material.map.image.width===768&&o.material.map.image.height===512){ if(o.geometry.attributes.uv.count>0&&o.geometry.index&&o.geometry.index.count/6===o.geometry.attributes.position.count/4&&o.position.y<0&&!floorMesh&&o.geometry.attributes.position.count>4000) floorMesh=o; else if(!pit&&o.position.y<0) pit=o; } if(o.isMesh&&o.geometry&&o.geometry.type==='PlaneGeometry'&&Math.abs(o.rotation.x+Math.PI/2)<1e-3&&o.position.y===0) plane=o; });
  let uvOk=true; const meshes=[floorMesh,pit].filter(Boolean); for(const m of meshes){ const U=m.geometry.attributes.uv; for(let i=0;i<U.count;i++){ const u=U.getX(i), v=U.getY(i); if(!(u>=0&&u<=1&&v>=0&&v<=1)){ uvOk=false; break; } } }
  return { floorMesh:!!floorMesh, pit:!!pit, planeHidden:plane?plane.visible===false:null, lowered:meshes.map(m=>m.position.y), uvOk }; });
check("the terraces' own floor mesh is repainted from the atlas, the pit has a floor of its own, the old painted plane is hidden, both lowered 0.12, every uv inside the atlas",B.floorMesh&&B.pit&&B.planeHidden===true&&B.lowered.every(y=>Math.abs(y+.12)<1e-6)&&B.uvOk,JSON.stringify(B));
const C=await page.evaluate(()=>{ const d=window.__dd, F=window.__prisonfloor; d.setHero(0,12,Math.PI); d.setCam(Math.PI,.5,9); for(let i=0;i<20;i++) d.step(1/60,1); const n1=F.info().near; const x1=window.__dd.hero.y; d.setHero(0,50,Math.PI); d.setCam(Math.PI,.5,9); for(let i=0;i<20;i++) d.step(1/60,1); const n2=F.info().near; const ms=F.kindsMeshes(); const camNear=ms.reduce((a,m)=>a+m.count,0); const tri=ms.reduce((a,m)=>a+m.count*m.geometry.index.count/3,0);
  const first=ms.find(m=>m.count>0); const mat=new THREE.Matrix4(), pp=new THREE.Vector3(), q=new THREE.Quaternion(), s=new THREE.Vector3(); first.getMatrixAt(0,mat); mat.decompose(pp,q,s); const cam=d.camera.position; return { n1, n2, camNear, tri, relief:+s.y.toFixed(2), within:Math.hypot(pp.x-cam.x,pp.z-cam.z)<20, heroY:+d.hero.y.toFixed(2), floorY:+d.floorH(d.hero.x,d.hero.z).toFixed(2) }; });
check("the real relief tiles are instanced near the camera only (a few dozen of the block tiles, well under 300,000 triangles), refilled as it moves, squashed to 60%",C.n1>8&&C.n1<400&&C.n2>8&&C.n2<400&&C.tri<300000&&C.relief===.6&&C.within,JSON.stringify(C));
check("the hero's feet are still on the floor",Math.abs(C.heroY-C.floorY)<.2,JSON.stringify({ heroY:C.heroY, floorY:C.floorY }));
check("nothing failed to load or build",warns.length===0,warns.join(' | '));
const realErrors=errors.filter(x=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(x)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
// ---- build 379: by default the tiles are OFF (the yellow was ruining the vibe): no tile model is even asked for, the game's own floor shows
{ const asked=[]; const p2=await (await browser.newContext({viewport:{width:900,height:560}})).newPage(); p2.on("request",r=>{ if(/prison-floor-\d/.test(r.url())) asked.push(r.url()); }); await p2.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
  await p2.goto("http://127.0.0.1:8991/?silent&nogate&map=5",{timeout:120000}); await p2.waitForFunction(()=>window.__dd&&window.__dd.map().id==='prison',null,{timeout:120000}); await sleep(2500);
  const off=await p2.evaluate(()=>{ const d=window.__dd, sc=typeof d.scene==='function'?d.scene():d.scene; let plane=null; sc.traverse(o=>{ if(!plane&&o.isMesh&&o.geometry&&o.geometry.type==='PlaneGeometry'&&Math.abs(o.rotation.x+Math.PI/2)<1e-3&&o.geometry.parameters.width>=90) plane=o; }); return { info:window.__prisonfloor.info(), planeVisible:!!(plane&&plane.visible), lowered:!!(window.__dd.worldInfo&&0) }; });
  check("by default (no ?floortiles) the six-tile floor is off: no tile model is requested, the hook says so, and the game's own floor plane is showing",asked.length===0&&off.info===null&&off.planeVisible,JSON.stringify({ asked:asked.length, off })); await p2.context().close(); }
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
