// ===== THE DEEP PRISON'S BREAKABLE WALLS (56g-prisonwalls.js, build 343; Bob's hi3d breakable wall). Matt: "that destructible wall will sit on 2 sides of the apex of the triangle and when broken a secret weapon comes out
// and starts to fire". Checked: two walls stand either side of the Heartroot's corner, facing into the pit, each with 48 pieces; a far-off swing does nothing; your sword swing in front of one takes 25 (four blows break it)
// and a swing behind you does nothing; a staff bolt hits one too; when one breaks the alcove behind opens (the stone cell becomes floor), a free Mark VI weapon is placed there (west: Ballista, east: Acorn Cannon), its mana
// and defense units handed back, unsellable, tougher than a built one; the weapon really fires on a goblin walking past; the other wall is untouched; the path to the Heartroot still exists; no page errors.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8998,{dist:process.env.DIST||"./dist"});
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const errors=[]; const warns=[];
const ctx=await browser.newContext({viewport:{width:900,height:560}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==='warning'&&/prison (walls|decor)/.test(m.text())) warns.push(m.text().slice(0,160)); });
await page.goto("http://127.0.0.1:8998/?silent&nogate&map=5&noshow",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__prisonwalls&&window.__dd.map()&&window.__dd.map().id==='prison',null,{timeout:120000});
await page.evaluate(()=>{ const d=window.__dd; try{ window.__trainer.skip(); }catch(e){} d.start(); d.step(1/60,5); });
let w=null; for(let i=0;i<300;i++){ w=await page.evaluate(()=>{ window.__dd.step(1/60,1); return window.__prisonwalls.walls(); }); if(w.length===2) break; await sleep(100); }
check("two breakable walls stand in the prison, one each side of the Heartroot's corner, both Bob's shackled wall (all 48 of his pieces each; the Meshy cracked wall is kept for the big barrier), each breathing a soft glow so it can be found, each 4 squares wide and 4 tall, in the apex's north wall one each side of the Heartroot, opening SOUTH, downfield",w.length===2&&w.find(x=>x.id==='W').kind==='hi3d'&&w.find(x=>x.id==='W').chunks===48&&w.find(x=>x.id==='E').kind==='hi3d'&&w.find(x=>x.id==='E').chunks===48&&w.every(x=>!x.broken&&x.health===100&&x.glow)&&w.some(x=>x.x<-9&&x.x>-13)&&w.some(x=>x.x>9&&x.x<13)&&w.every(x=>x.z>-3.5&&x.z<-.5),JSON.stringify(w));
// ---- build 367 (Matt: "we need the mortar rooms to glow and some kind of prompt to the player"): the rooms start LOCKED until the big barrier falls, then WAKE
const L1=await page.evaluate(()=>{ const d=window.__dd, M=window.__mortarwake; const raw=window.__prisonwalls.raw(); const locked0=raw.map(w=>!!w.locked); const beaconVis0=raw.map(w=>w.beacon.gs.visible); d.setHero(-11,1.5,Math.PI); d.setCam(Math.PI,.3,6); d.swing(); for(let i=0;i<50;i++) d.step(1/60,1); const hp=window.__prisonwalls.walls().map(w=>w.health); return { locked0, beaconVis0, hp, awake:M.info().awake }; });
check("the two rooms start LOCKED and dark: no beacon, and a sword swung right at one does nothing, until the big barrier has fallen",L1.locked0.every(Boolean)&&L1.beaconVis0.every(v=>v===false)&&L1.hp.every(h=>h===100)&&!L1.awake,JSON.stringify(L1));
const W0=await page.evaluate(()=>{ const d=window.__dd, M=window.__mortarwake; const ok=M.wake(); for(let i=0;i<30;i++) d.step(1/60,1); const raw=window.__prisonwalls.raw(); const i=M.info(); return { ok, locked:raw.map(w=>!!w.locked), vis:raw.map(w=>w.beacon.gs.visible), light:raw.map(w=>+w.beacon.gl.intensity.toFixed(2)), op:raw.map(w=>+w.beacon.gs.material.opacity.toFixed(2)), scale:raw.map(w=>+w.beacon.gs.scale.x.toFixed(0)), glow:i.glow, lost:i.lost, card:!!document.getElementById('mortarcard'), arrows:document.querySelectorAll('.mwarrow').length }; });
check("waking them (the barrier has fallen) unlocks both rooms with a VERY SLIGHT glow (build 383): showing, but dim and small (opacity under .25, light under .6, the base size), and no card, no arrow, no tip of any kind",W0.ok&&W0.locked.every(l=>!l)&&W0.vis.every(Boolean)&&W0.op.every(v=>v<.25&&v>0)&&W0.light.every(v=>v<.6&&v>0)&&W0.scale.every(v=>v<=14)&&W0.glow===0&&!W0.card&&W0.arrows===0,JSON.stringify(W0));
const W1=await page.evaluate(()=>{ const d=window.__dd, M=window.__mortarwake; const read=()=>{ const raw=window.__prisonwalls.raw(); for(let i=0;i<20;i++) d.step(1/60,1); return { glow:M.info().glow, op:+Math.max(...raw.map(w=>w.beacon.gs.material.opacity)).toFixed(2), light:+Math.max(...raw.map(w=>w.beacon.gl.intensity)).toFixed(2), scale:+Math.max(...raw.map(w=>w.beacon.gs.scale.x)).toFixed(0) }; };
  const out={}; M.lose(2); out.two=read(); M.lose(1); out.three=read(); M.lose(3); out.six=read(); M.lose(4); out.ten=read(); return out; });
check("the first two defenses lost change nothing; from the THIRD the glow swells with each one the horde takes out (an eighth more each), and at ten it is the big hot glow (scale 19+, a strong light)",W1.two.glow===0&&W1.three.glow>0&&W1.three.glow<W1.six.glow&&W1.six.glow<W1.ten.glow&&W1.ten.glow===1&&W1.three.op>W1.two.op&&W1.six.op>W1.three.op&&W1.ten.op>.5&&W1.ten.light>2.4&&W1.ten.scale>=19,JSON.stringify(W1));
const W2=await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*30;i++) d.step(1/60,1); return { card:!!document.getElementById('mortarcard'), arrows:document.querySelectorAll('.mwarrow').length, pillars:0 }; });
check("and nothing ever tells the player: thirty seconds on there is still no card and no arrow",!W2.card&&W2.arrows===0,JSON.stringify(W2));
await page.evaluate(()=>window.__heroes.select('knight')); await page.waitForFunction(()=>/Knight/.test(window.__dd.heroModel().label),null,{timeout:120000});
const base=await page.evaluate(()=>{ const d=window.__dd; return { defs:d.defs.length, mana:d.S.mana, du:d.S.du }; });
// a swing from far away does nothing; a swing with your back to it does nothing
const far=await page.evaluate(async()=>{ const d=window.__dd; d.setHero(0,22,Math.PI); d.setCam(Math.PI,.3,6); d.swing(); for(let i=0;i<40;i++) d.step(1/60,1); return window.__prisonwalls.walls().map(x=>x.health); });
const back=await page.evaluate(async()=>{ const d=window.__dd; d.setHero(-11,1.5,0); d.setCam(0,.3,6); d.swing(); for(let i=0;i<40;i++) d.step(1/60,1); return window.__prisonwalls.walls().map(x=>x.health); });
check("a swing from across the pit, or with your back to a wall, does not touch it",far.every(h=>h===100)&&back.every(h=>h===100),JSON.stringify({far,back}));
// swings in front of the west wall: four blows of 25
const hp=[]; for(let k=0;k<4;k++){ const h=await page.evaluate(async()=>{ const d=window.__dd; d.setHero(-11,1.5,Math.PI); d.setCam(Math.PI,.3,6); d.swing(); for(let i=0;i<50;i++) d.step(1/60,1); return window.__prisonwalls.walls().find(x=>x.id==='W').health; }); hp.push(h); }
check("swinging your sword at the west wall takes 25 a blow: 75, 50, 25, then it breaks (0)",JSON.stringify(hp)==="[75,50,25,0]",JSON.stringify(hp));
const after=await page.evaluate(async()=>{ const d=window.__dd; for(let i=0;i<120;i++) d.step(1/60,1); return { walls:window.__prisonwalls.walls(), spots:window.__prisonwalls.spots(), defs:d.defs.length, mana:d.S.mana, du:d.S.du, cell:d.cellAt?d.cellAt(18,6):null }; });
const W=after.spots.find(s=>s.id==='W'), E=after.spots.find(s=>s.id==='E');
check("the west wall bursts, the alcove opens and a free Mark VI lobbing weapon is placed in it, resting facing straight out of its room, south, down the field -- secret, tougher than a built one; the east wall and its weapon are untouched",after.walls.find(x=>x.id==='W').broken&&W.open&&W.def.kind==='ball'&&Math.abs(W.def.rot)<.01&&W.def.lvl===6&&W.def.secret&&W.def.max>=2*120&&!E.open&&!after.walls.find(x=>x.id==='E').broken,JSON.stringify({W,E}));
check("the weapon cost nothing: your mana and defense units are as they were, and it is the only new defense",after.defs===base.defs+1&&after.mana===base.mana&&after.du===base.du,JSON.stringify({base,after:{defs:after.defs,mana:after.mana,du:after.du}}));
// it fires: a goblin walks past in front of it
const fire=await page.evaluate(async()=>{ const d=window.__dd; d.S.crystal=1e6; d.S.phase='wave'; d.setHero(0,30,Math.PI); d.spawn('goblin','W'); const e=d.enemies[d.enemies.length-1]; const hp0=e.hp; let proj=0, bombs=0, dead=false; const d0=d.defs.find(x=>x.secret);
  e.x=-11; e.z=8; e.spd=0; for(let i=0;i<600&&!e.dead;i++){ d.step(1/60,1); d.S.crystal=1e6; if(d.projs.some(p=>p.kind==='turnip')){ proj++; if(d.projs.some(p=>p.kind==='turnip'&&p.mesh&&p.mesh.getObjectByName('hexbomb'))) bombs++; } } const mort=window.__prisonwalls.mortars(); const bl=window.__blight.info(); return { bombs, cloudsMade:bl.cloudsMade, proj, hp0, hp:e.hp, dead:!!e.dead, kills:d.S.kills, mort }; });
check("Bob's Hex Mortar fires on a goblin in its range (shells in the air, the 'Fire' clip played, the goblin hurt or dead)",fire.proj>0&&(fire.dead||fire.hp<fire.hp0)&&fire.mort.length>=1&&fire.mort[0].rolled&&fire.mort[0].fires>=1&&fire.mort[0].hasMuzzle&&fire.mort[0].clips.includes('Fire')&&fire.mort[0].clips.includes('Roll'),JSON.stringify(fire));
// the east wall breaks to the witch's staff bolts
await page.evaluate(()=>window.__heroes.select('witch')); await page.waitForFunction(()=>/Witch/.test(window.__dd.heroModel().label),null,{timeout:120000});
const eh=await page.evaluate(async()=>{ const d=window.__dd, P=window.__prisonwalls; const hp=[]; for(let k=0;k<14&&!P.walls().find(x=>x.id==='E').broken;k++){ d.setHero(11,1.5,Math.PI); d.setCam(Math.PI,.3,6); d.swing(); for(let i=0;i<60;i++){ d.step(1/60,1); d.S.crystal=1e6; } hp.push(P.walls().find(x=>x.id==='E').health); } for(let i=0;i<150;i++) d.step(1/60,1); return { hp, broken:P.walls().find(x=>x.id==='E').broken, spots:P.spots() }; });
check("the witch's staff bolts break the east wall too (it loses health as they land, then bursts) and its Hex Mortar rolls out",eh.broken&&eh.hp.some(h=>h<100)&&eh.spots.find(s=>s.id==='E').def&&eh.spots.find(s=>s.id==='E').def.kind==='ball'&&eh.spots.find(s=>s.id==='E').def.lvl===6,JSON.stringify(eh));
const sold=await page.evaluate(async()=>{ const d=window.__dd; const s=d.defs.filter(x=>x.secret); const before=d.defs.length; const mana0=d.S.mana; s.forEach(x=>{ try{ d.setHero(x.x,x.z+1.6,Math.PI); d.setCam(Math.PI,.3,6); d.sell(); }catch(e){} }); return { secret:s.length, before, after:d.defs.length, mana:d.S.mana-mana0 }; });
const blocked=await page.evaluate(()=>{ const d=window.__dd, sc=typeof d.scene==='function'?d.scene():d.scene; const m=new THREE.Matrix4(), v=new THREE.Vector3(), q=new THREE.Quaternion(), s=new THREE.Vector3(); const hits=[]; sc.traverse(o=>{ if(!o.isInstancedMesh||o.count<20) return; for(let i=0;i<o.count;i++){ o.getMatrixAt(i,m); m.decompose(v,q,s); if(Math.abs(v.x)>7.5&&Math.abs(v.x)<14.5&&v.z>-5&&v.z<-1.2&&v.y<7.5) hits.push([+v.x.toFixed(1),+v.y.toFixed(1),+v.z.toFixed(1)]); } }); return hits.slice(0,5); });
check("nothing is left standing in either opened alcove (no wall modules, no sconces inside the 4-by-4 opening)",blocked.length===0,JSON.stringify(blocked));
check("a secret weapon cannot be sold",sold.secret===2&&sold.after===sold.before,JSON.stringify(sold));
const path=await page.evaluate(()=>window.__prisondecor.reach()); check("every breakout still has its route to the Heartroot (the alcoves are dead ends)",path.E>0&&path.S>0&&path.W>0&&path.NE>0,JSON.stringify(path));
check("the mortar's shell is Matt's Hex Canister Bomb, tumbling as it flies, and where it lands the blight blast and a short green cloud go off",fire.bombs>0&&fire.cloudsMade>=1,JSON.stringify({bombs:fire.bombs,clouds:fire.cloudsMade}));
const reach=await page.evaluate(async()=>{ const d=window.__dd; window.__blight.clear(); d.S.phase='wave'; d.S.crystal=1e6; const W=d.defs.find(x=>x.secret&&x.x<0); const tre=d.placeDefAt('ball',30,-2,0); const base=d.stat(tre,'range'), mine=d.stat(W,'range'); d.defs.splice(d.defs.indexOf(tre),1); try{ d.sell&&0; }catch(e){}
  d.enemies.forEach(e=>{ if(!e.dead){ e.dead=.001; } });
  const mk=(x,z)=>{ d.spawn('orc','E'); const e=d.enemies[d.enemies.length-1]; e.x=x; e.z=z; e.spd=0; e.hp=e.max=1e6; return e; };
  const near=mk(-11,14); for(const [dx,dz] of [[0,0],[1.6,0],[0,1.6],[1.6,1.6],[-1.6,0],[0,-1.6]]) mk(-11+dx,36+dz);
  let at=null; for(let i=0;i<60*10&&!at;i++){ d.step(1/60,1); d.S.crystal=1e6; const c=window.__blight.cloudAt(); if(c.length) at=c[0]; }
  return { base, mine, at }; });
check("the secret mortar reaches far downfield (1.8 times a built trebuchet range) and lobs at the THICKEST cluster (six mobs 36 away, not the lone one 14 away) where the mist bursts",reach.mine>=reach.base*1.7&&reach.at&&Math.abs(reach.at.z-36)<5,JSON.stringify(reach));
check("no model failed to load",warns.length===0,warns.slice(0,3).join(' | '));
// both rooms are open by now: their pillars, arrows and the card are gone
const Z=await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*10;i++) d.step(1/60,1); const i=window.__mortarwake.info(); return { broken:window.__prisonwalls.walls().map(w=>w.broken), pillars:i.pillars, arrows:i.arrows, card:i.card }; });
check("both rooms broken at last (the show is off in this test)",Z.broken.every(Boolean),JSON.stringify(Z));
const realErrors=errors.filter(e=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(e)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
