// ===== THE BIG BARRIER (56i-prisonbarrier.js, build 363). Matt: "you come in about 3 tiles and put up a big wall, but the bottom row is breakable, i am wondering if we can have the boss break one and chain reaction the whole
// thing, maybe its a quick cutscene?". Checked: the wall of Meshy panels (two rows of thirteen) stands across the rim with the last three rows solid behind it and the rim's two gates in front of it; nothing the hero or a mob
// does gets through; the cutscene (started from the dev hook, or by the sixth wave sixteen seconds in) holds the game still, brings in the boss, breaks ONE bottom panel first and the rest after it in a ripple (the ones above
// after the ones beneath), opens the three rows and shows the crowd standing in them -- torches lit -- then hands the game back with the crowd coming out; the wall can be put back; the lights never change; no page errors.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8997,{dist:process.env.DIST||"./dist"});
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const errors=[];
const ctx=await browser.newContext({viewport:{width:900,height:560}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e)));
await page.goto("http://127.0.0.1:8997/?silent&nogate&map=5",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__finale&&window.__carts&&window.__torchmobs&&window.__dd.map().id==='prison',null,{timeout:120000});
await page.evaluate(async()=>{ try{ window.__trainer.skip(); }catch(e){} const d=window.__dd; d.start(); d.step(1/60,5); window.__freeze=true; await Promise.all(window.__carts.kinds.map(k=>window.__carts.load(k))); });
for(let i=0;i<80;i++){ const r=await page.evaluate(()=>{ window.__dd.step(1/60,1); return window.__finale.ready(); }); if(r) break; await new Promise(r=>setTimeout(r,250)); }
// ---- the wall
const A=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale, g=F.geom, i=F.info(); const GW=d.map().gw; const cells=F.strip(); const tiles=cells.map(c=>d.grid[c]); const pl=F.panelList(); const L=typeof d.lanes==='function'?d.lanes():d.lanes; const lanes=Object.fromEntries(Object.entries(L).map(([k,l])=>[k,[l.cx,l.cz]]));
  return { panels:i.panels, rows:[...new Set(pl.map(p=>p.r))].length, cols:[...new Set(pl.map(p=>p.c))].length, tiles:tiles.length, solid:tiles.every(t=>t===0), sealed:i.sealed, backing:i.backing, X0:g.X0, X1:g.X1, BZ:g.BZ, lanes, GW }; });
check("a wall of 26 panels (two rows of thirteen) stands across the rim, the last three rows (129 tiles) solid behind it and a backing behind the seams",A.panels===26&&A.rows===2&&A.cols===13&&A.tiles===129&&A.solid&&A.sealed&&A.backing,JSON.stringify({ panels:A.panels, rows:A.rows, cols:A.cols, tiles:A.tiles, solid:A.solid, backing:A.backing }));
check("the rim's two gates stand in front of it, at the east end and the west end, and the other two are where they were",JSON.stringify(A.lanes)===JSON.stringify({ E:[45,41], S:[1,41], W:[7,28], NE:[34,19] }),JSON.stringify(A.lanes));
const LK=await page.evaluate(()=>{ const i=window.__mortarwake.info(); return { awake:i.awake, locked:i.locked }; });
check("until the wall falls the two mortar rooms by the Heartroot are locked (dark, no blows count)",!LK.awake&&LK.locked.length===2&&LK.locked.every(Boolean),JSON.stringify(LK));
const B=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; const g=F.geom; d.S.phase='build'; d.setHero(0,g.BZ-8,0); d.cam.yaw=0; d.setKeys({ w:1 }); let maxZ=-1e9; for(let i=0;i<60*4;i++){ d.cam.yaw=0; d.step(1/60,1); maxZ=Math.max(maxZ,d.hero.z); } d.setKeys({ w:0 }); return { maxZ:+maxZ.toFixed(2), wallZ:+g.BZ.toFixed(2), z:+d.hero.z.toFixed(2) }; });
check("the hero cannot walk into the wall (walking south into it for four seconds he stops at its face)",B.maxZ<B.wallZ&&B.maxZ>B.wallZ-1.5,JSON.stringify(B));
const C=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; const g=F.geom; for(const e of d.enemies) if(!e.dead) e.dead=.001; d.S.phase='wave'; d.S.crystal=1e6; const out={}; for(const L of ['E','S']){ d.spawn('goblin',L); const e=d.enemies[d.enemies.length-1]; e.hp=e.max=1e9; out[L]={ e, z0:e.z, x0:e.x }; }
  let minZ={E:1e9,S:1e9}; let maxZ={E:-1e9,S:-1e9}; for(let i=0;i<60*14;i++){ d.step(1/60,1); d.S.crystal=1e6; for(const L of ['E','S']){ const e=out[L].e; minZ[L]=Math.min(minZ[L],e.z); maxZ[L]=Math.max(maxZ[L],e.z); } }
  return { start:{ E:[+out.E.x0.toFixed(1),+out.E.z0.toFixed(1)], S:[+out.S.x0.toFixed(1),+out.S.z0.toFixed(1)] }, minZ, maxZ, BZ:g.BZ }; });
check("mobs from the rim's two gates come out in front of the wall and walk away from it, none ever behind its face",C.maxZ.E<C.BZ&&C.maxZ.S<C.BZ&&C.minZ.E<C.start.E[1]-3&&C.minZ.S<C.start.S[1]-3,JSON.stringify(C));
// ---- the cutscene
const lights0=await page.evaluate(()=>{ const d=window.__dd, sc=typeof d.scene==='function'?d.scene():d.scene; let n=0; sc.traverse(o=>{ if(o.isLight) n++; }); return n; });
await page.evaluate(async()=>{ await window.__corruptor.load(); });
const D=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; for(const e of d.enemies) if(!e.dead) e.dead=.001; d.step(1/60,5); d.setHero(0,50,0); d.S.phase='wave'; d.S.crystal=1e6; d.S.waveT=3; const hp0=d.hero.hp; const w0=d.S.waveT; const ok=F.start(); const bars=[...document.querySelectorAll('div')].filter(x=>/z-index:\s*90/.test(x.getAttribute('style')||''));
  const T=F.times; const at=(t)=>{ const need=Math.round(t*60)-Math.round(F.info().t*60); for(let i=0;i<need;i++){ d.step(1/60,1); d.S.crystal=1e6; } };
  at(1.0); const cam1=d.camera.position.toArray().map(v=>+v.toFixed(1)); const waveT1=d.S.waveT; const boss=F.boss(); const bx1=boss.x; const hover1=0;
  at(T.T_RUN+.4); const bossAtWall=Math.abs(boss.x-F.geom.XS)<3; const cor=window.__corruptor.info(); const clipName=()=>boss.mdl.cur?boss.mdl.cur.getClip().name:null; const clipRoar=clipName(); at(T.T_CAST+.4); const clipCast=clipName(); at(T.T_SWING+.3); const clipAttack=clipName();
  at(T.T_HIT-.15); const preBroken=F.info().broken; at(T.T_HIT+.1); const first=F.panelList().filter(p=>p.broken).map(p=>[p.r,p.c]); const snips=window.__corruptor.info().snips;
  at(T.T_HIT+.5); const mid=F.info(); at(T.T_OPEN+.1); const opened=F.info();
  const pl=F.panelList(); const byC=c=>pl.filter(p=>p.c===c); const mono=[1,2,3,4,5,6].every(k=>byC(6+k).find(p=>p.r===0).tb>byC(6+k-1).find(p=>p.r===0).tb&&byC(6-k).find(p=>p.r===0).tb>byC(6-k+1).find(p=>p.r===0).tb); const upper=pl.filter(p=>p.r===1).every(p=>p.tb>pl.find(q=>q.r===0&&q.c===p.c).tb);
  const cr=F.crowd().filter(e=>!e.dead); const g=F.geom; const inStrip=cr.filter(e=>e.z>g.BZ+1&&e.z<g.ZB).length; const teams=d.enemies.filter(e=>!e.dead&&(e.kind==='kegcart'||e.kind==='firecart')); const crewIn=teams.every(c=>c.crew.every(o=>o.z>g.BZ&&o.z<g.ZB+1)); const torches=window.__torchmobs.info(); const kinds=[...new Set(cr.map(e=>e.kind))].sort();
  at(17.5); const mu1=window.__bossMusic.info().stage; at(18.4); const mu2=window.__bossMusic.info().stage; at(T.T_GO-.3); const mu3=window.__bossMusic.info().stage; const wT0=d.S.waveT; at(T.T_GO+.1); const mu4=window.__bossMusic.info().stage; const wT1=d.S.waveT; at(T.T_END-.3); const late=F.info(); const crAfter=F.crowd().filter(e=>!e.dead); const out=crAfter.filter(e=>e.z<g.BZ-2).length; const heroHp=d.hero.hp;
  return { ok, bars:bars.length, barH:bars.map(b=>b.style.height), cam1, waveT0:w0, waveT1, boss:!!boss&&boss.kind==='corruptor', clipRoar, clipCast, clipAttack, mu:[mu1,mu2,mu3,mu4], bx1:+bx1.toFixed(1), bossAtWall, cor, preBroken, first, snips, midBroken:mid.broken, open:opened.open, sealedAtOpen:opened.sealed, mono, upper, inStrip, carts:teams.length, crewIn, torches:torches.alive, kinds, runsAfterGo:wT1>wT0, lateBroken:late.broken, active:late.active, out, heroHp, hp0 }; });
check("the cutscene starts (black bars in), the game holds still while the boss comes in (the wave clock does not move), the camera is its own and the boss (the Corruptor stand-in) hovers off the floor and charges to the strike point",D.ok&&D.bars===2&&D.barH.every(h=>h==='12vh')&&D.waveT1===D.waveT0&&D.cam1[2]<60&&D.boss&&D.clipRoar==='roar'&&D.bossAtWall,JSON.stringify({ ok:D.ok, bars:D.bars, barH:D.barH, w:[D.waveT0,D.waveT1], cam:D.cam1, boss:D.boss, clips:[D.clipRoar,D.clipCast,D.clipAttack], atWall:D.bossAtWall }));
check("the boss acts out the build-up with its own clips: the roar when it arrives at the wall, then the cast (all four arms raised), then the attack (the shears), each at its time",D.clipRoar==='roar'&&D.clipCast==='cast'&&D.clipAttack==='attack',JSON.stringify({ roar:D.clipRoar, cast:D.clipCast, attack:D.clipAttack }));
check("the score follows the cinematic: boss 1 until 18 s, boss 2 for 11 s (18-29), then Drums from the Depths as the horde is let out",D.mu[0]==='boss1'&&D.mu[1]==='boss2'&&D.mu[2]==='boss2'&&D.mu[3]==='battle',JSON.stringify(D.mu));
check("nothing breaks until the boss's blow lands (its snip flashes there); then ONE bottom panel (the middle one) goes first",D.preBroken===0&&D.first.length===1&&D.first[0][0]===0&&D.first[0][1]===6&&D.snips>=1,JSON.stringify({ pre:D.preBroken, first:D.first, snips:D.snips }));
check("the break ripples out along the wall (a few panels half a second on) and the three rows open with the crowd standing in them",D.midBroken>=4&&D.midBroken<26&&D.open&&D.sealedAtOpen===false&&D.inStrip>=90,JSON.stringify({ mid:D.midBroken, open:D.open, inStrip:D.inStrip }));
check("the chain is in order: each bottom panel breaks after its neighbour nearer the middle, each upper panel after the one beneath it",D.mono&&D.upper,JSON.stringify({ mono:D.mono, upper:D.upper }));
check("what stands in the dark: ~100 mobs (goblins, orcs, bandits, ogres) inside the three rows, carts with their orcs, and some of them carry torches",D.inStrip>=90&&D.carts>=3&&D.crewIn&&D.torches>=3&&D.kinds.includes('goblin')&&D.kinds.includes('orc')&&D.kinds.includes('archer'),JSON.stringify({ inStrip:D.inStrip, carts:D.carts, crewIn:D.crewIn, torches:D.torches, kinds:D.kinds }));
check("then the game runs again with the bars still on and the camera still watching: the whole crowd pours out at once (dozens already out in front of where the wall was) and the hero, held still, is untouched; all twenty-six panels are down",D.runsAfterGo&&D.out>=30&&D.lateBroken===26&&D.active&&D.heroHp>=D.hp0,JSON.stringify({ runs:D.runsAfterGo, out:D.out, broken:D.lateBroken, active:D.active, hp:[D.hp0,D.heroHp] }));
const F2=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; const t0=F.info(); const lit=window.__torchmobs.lights().map(l=>({ i:+l.intensity.toFixed(2), x:+l.position.x.toFixed(0), z:+l.position.z.toFixed(0) })).filter(l=>l.i>.3);
  for(let i=0;i<40;i++){ d.step(1/60,1); d.S.crystal=1e6; } const t1=F.info(); const w=d.S.waveT; for(let i=0;i<180;i++){ d.step(1/60,1); d.S.crystal=1e6; } const w2=d.S.waveT; const barH=[...document.querySelectorAll('div')].filter(x=>/z-index:\s*90/.test(x.getAttribute('style')||'')).map(b=>b.style.height);
  const cr=F.crowd().filter(e=>!e.dead); const g=F.geom; const out=cr.filter(e=>e.z<g.BZ-4).length; const sc=typeof d.scene==='function'?d.scene():d.scene; let n=0; sc.traverse(o=>{ if(o.isLight) n++; }); return { activeEnd:t1.active, done:t1.done, wave:[w,w2], barH, out, crowd:cr.length, later:F.info().later, litFar:lit.filter(l=>l.z>70).length, lights:n }; });
check("when it ends the bars slide away, the game goes on (the wave clock runs again) and more of the crowd comes out of the dark every half second",!F2.activeEnd&&F2.done&&F2.wave[1]>F2.wave[0]+2&&F2.barH.every(h=>h==='0px'||h==='0')&&F2.out>=30&&F2.later>=1,JSON.stringify(F2));
check("the lights do not change (a fixed pool: the torches' own four, nothing added)",F2.lights===lights0,JSON.stringify({ before:lights0, after:F2.lights }));
const G=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; for(const e of d.enemies) if(!e.dead) e.dead=.001; const ok=F.reset(); const i=F.info(); return { ok, intact:i.intactPanels, sealed:i.sealed, done:i.done, backing:i.backing, relocked:window.__mortarwake.info().locked.every(Boolean)&&!window.__mortarwake.info().awake }; });
check("the wall can be put back whole (panels intact, the three rows solid, ready to fall again)",G.ok&&G.intact===26&&G.sealed&&!G.done&&G.backing&&G.relocked,JSON.stringify(G));
// ---- the skip button: straight to the drums, the wall down, the crowd out
const SK=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; for(const e of d.enemies) if(!e.dead) e.dead=.001; d.S.phase='wave'; d.S.crystal=1e6; F.reset(); F.start(); for(let i=0;i<60*3;i++){ d.step(1/60,1); d.S.crystal=1e6; } const nb=()=>F.panelList().filter(p=>p.broken).length; const before={ broken:nb() }; const ok=F.skip(); for(let i=0;i<30;i++){ d.step(1/60,1); d.S.crystal=1e6; } const i2=Object.assign(F.info(),{ broken:nb() }); const mu=window.__bossMusic.info().stage; const btn=[...document.querySelectorAll('div')].find(x=>x.textContent==='\u23ED'); const btnOff=btn&&btn.style.pointerEvents==='none';
  for(let i=0;i<60*8;i++){ d.step(1/60,1); d.S.crystal=1e6; } const i3=F.info(); return { ok, brokenBefore:before.broken, broken:i2.broken, open:i2.open, crowd:i2.crowdNow, mu, btnOff, activeAfter:i2.active, doneEnd:i3.done }; });
check("the skip button (or Enter) jumps the cutscene to its end-point: the wall is down, the three rows open, the whole crowd out, Drums from the Depths on, the button gone; the bars come off a few seconds later",SK.ok&&SK.brokenBefore===0&&SK.broken===26&&SK.open&&SK.crowd>=90&&SK.mu==='battle'&&SK.btnOff&&SK.activeAfter&&SK.doneEnd,JSON.stringify(SK));
await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; for(const e of d.enemies) if(!e.dead) e.dead=.001; F.reset(); window.__bossMusic.stop(.1,false); });
// ---- the sixth wave does it by itself, sixteen seconds in; the wave cannot end before it
const H=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; for(const e of d.enemies) if(!e.dead) e.dead=.001; d.S.phase='build'; d.S.wave=5; d.S.crystal=1e6; d.setHero(0,50,0); d.startWave(); const w=d.S.wave, ph=d.S.phase; let early=false; for(let i=0;i<60*6;i++){ d.step(1/60,1); d.S.crystal=1e6; if(i===60*3) for(const e of d.enemies) if(!e.dead) e.dead=.001; }
  const stillWave=d.S.phase==='wave'&&!F.info().active&&!F.info().done; let startedAt=null; for(let i=0;i<60*14&&startedAt===null;i++){ d.step(1/60,1); d.S.crystal=1e6; if(F.info().active) startedAt=+d.S.waveT.toFixed(1); } return { w, ph, stillWave, startedAt }; });
check("the sixth wave starts the cutscene on its own, sixteen seconds in, and the wave cannot end before it even if every mob is dead",H.w===6&&H.ph==='wave'&&H.stillWave&&H.startedAt!==null&&H.startedAt>=15.9&&H.startedAt<=16.3,JSON.stringify(H));
const I=await page.evaluate(()=>{ const d=window.__dd, F=window.__finale; for(let i=0;i<60*40;i++){ d.step(1/60,1); d.S.crystal=1e6; } const i=F.info(); const mw=window.__mortarwake.info(); return { done:i.done, active:i.active, open:i.open, crowd:i.crowdNow, awake:mw.awake, locked:mw.locked, arrows:mw.arrows, pillars:mw.pillars }; });
check("and plays through to the end (the wall down, the rows open, the game going on)",I.done&&!I.active&&I.open&&I.crowd>=90,JSON.stringify(I));
check("the moment the cinematic ends the two mortar rooms WAKE: unlocked, a pillar of light and a gold arrow for each",I.awake&&I.locked.every(l=>!l)&&I.pillars===2&&I.arrows===2,JSON.stringify({ awake:I.awake, locked:I.locked, pillars:I.pillars, arrows:I.arrows }));
// ---- the siege carts stay straight (Matt: "the two siege machines turn perpendicular to the line. they need to stay straight"): through the crowd's march, a moving cart faces the way it is going
const J=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) if(!e.dead&&e.kind!=='kegcart'&&e.kind!=='firecart'&&!e.pushFor) { e.hp=e.max=1e9; } const last={}; let samples=0, bad=0, worst=0;
  for(let i=0;i<60*22;i++){ d.step(1/60,1); d.S.crystal=1e6; if(i%30===0){ for(const e of d.enemies){ if(e.dead||(e.kind!=='kegcart'&&e.kind!=='firecart')) continue; const l=last[d.enemies.indexOf(e)]; if(l&&e.walking&&e.swing<0){ const dx=e.x-l.x, dz=e.z-l.z; if(Math.hypot(dx,dz)>.6){ let df=e.yaw-Math.atan2(dx,dz); df=Math.abs(Math.atan2(Math.sin(df),Math.cos(df))); samples++; if(df>.9) bad++; worst=Math.max(worst,df); } } last[d.enemies.indexOf(e)]={ x:e.x, z:e.z }; } } }
  return { samples, bad, worst:+worst.toFixed(2), carts:d.enemies.filter(e=>!e.dead&&(e.kind==='kegcart'||e.kind==='firecart')).length }; });
check("the siege carts stay straight: through the march a moving cart faces the way it is going (within about fifty degrees nine times in ten, never turned across its line of travel)",J.samples>=20&&J.bad<=J.samples*.1&&J.worst<2.4,JSON.stringify(J));
const realErrors=errors.filter(x=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(x)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
