// ===== THE MORTAR SHOW (build 383; parts/staging/95q-mortarshow.js, 95n-mortarwake.js, 56g-prisonwalls.js). Matt: "when i break the first door a cut scene, about 20 seconds long showing the mortars roll out a victory fanfair, and the launching of
// projectiles, the mist and the horde fighting itself ... make it fun to watch" (and no tool tip). Checked: breaking the first door starts it (black bars in, the hero held and untouchable, deaf to the keys); the second door bursts open by itself;
// both mortars roll out; the fanfare sounds and gold sparks fly; eight scripted volleys fly (the mortars fire only those -- their own fire is held -- and every shell is free: ammo is full at the end); the green mist blooms and MADDENS the horde (they
// fight each other); it ends at about 23.5 seconds, the bars slide away and the camera is handed back; the horde, meanwhile, was running all along; Enter skips it (and both doors are open); it plays once; it does not play in a co-op hall.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8997,{dist:process.env.DIST||"./dist"});
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--autoplay-policy=no-user-gesture-required"]}); const errors=[];
async function open(q){ const page=await (await browser.newContext({viewport:{width:900,height:560}})).newPage(); page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(m.type()==='warning'&&/mortar|show|prison/i.test(m.text())) errors.push("warn: "+m.text().slice(0,160)); });
  await page.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
  await page.goto("http://127.0.0.1:8997/?silent&nogate&map=5"+(q||""),{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__mortarshow&&window.__mortarshow.times&&window.__prisonwalls&&window.__prisonwalls.mounts&&window.__blight&&window.__dd.map().id==='prison',null,{timeout:120000}); await sleep(5000);
  await page.evaluate(()=>{ try{ window.__trainer.skip(); }catch(e){} const d=window.__dd; d.start(); d.step(1/60,5); d.S.crystal=1e9; d.S.mana=9999; d.S.phase='wave'; d.setHero(0,10,Math.PI);
    const kinds=['goblin','goblin','goblin','orc','goblin','archer','orc','goblin']; for(let i=0;i<80;i++){ d.spawn(kinds[i%kinds.length],['E','S','W','NE'][i%4]); const e=d.enemies[d.enemies.length-1]; if(!e) continue; e.hp=e.max=1e6; const k=i%3; e.x=(Math.random()-.5)*34+(k-1)*8; e.z=14+Math.random()*16; e.spd=.25; e.dmg=1; }
    window.__mortarwake.wake(); });
  return page; }
const breakFirst=page=>page.evaluate(()=>{ const w=window.__prisonwalls.raw().find(q=>!q.broken); w.locked=false; return w.hit(1e9,new window.THREE.Vector3(w.spot.cx0,2,w.spot.cz0),new window.THREE.Vector3(0,0,-1)); });
// ================= the whole show =================
{ const page=await open();
  const S=await page.evaluate(()=>{ const d=window.__dd, M=window.__mortarshow;
    const hp0=d.hero.hp, hx=d.hero.x, hz=d.hero.z; const w=window.__prisonwalls.raw().find(q=>!q.broken); w.locked=false; w.hit(1e9,new window.THREE.Vector3(w.spot.cx0,2,w.spot.cz0),new window.THREE.Vector3(0,0,-1));
    const t0=M.info(); const seen={}; const mark=(k,v)=>{ if(seen[k]===undefined) seen[k]=v; }; let maxMad=0, minHp=hp0, cams=new Set(); const keys={ w:1 }; d.setKeys(keys);
    for(let f=0;f<60*30;f++){ d.step(1/60,1); d.S.crystal=1e9; const t=(f+1)/60, i=M.info(); const raw=window.__prisonwalls.raw(), mounts=window.__prisonwalls.mounts();
      if(raw.every(q=>q.broken)) mark('bothBroken',t); if(mounts.length===2) mark('twoMounts',t); if(mounts.length===2&&mounts.every(m=>m.rolled)) mark('bothRolled',t); if(i.ev.fan) mark('fan',t); if(i.sparks>0) mark('sparks',t); if(i.volleys>=1) mark('v1',t); if(i.volleys>=8) mark('v8',t); if(!i.active&&i.done) mark('end',t);
      maxMad=Math.max(maxMad,d.enemies.filter(e=>!e.dead&&e.madT>0).length); if(i.active){ minHp=Math.min(minHp,d.hero.hp); window.__heroDuring=[+d.hero.x.toFixed(2),+d.hero.z.toFixed(2)]; window.__firesDuring=mounts.map(m=>m.fires); } if(i.active&&Math.floor(t)%4===0) cams.add(d.camera.position.toArray().map(v=>Math.round(v)).join(',')); if(t>8&&t<8.1) mark('barsDuring',i.bars.join('|')); }
    d.setKeys({ w:0 }); const fin=M.info();
    return { t0:{ active:t0.active, bars:t0.bars, first:t0.first, second:t0.second }, seen, maxMad, minHp, hp0, hero:window.__heroDuring, hero0:[+hx.toFixed(2),+hz.toFixed(2)], cams:cams.size, fin:{ active:fin.active, done:fin.done, volleys:fin.volleys, shells:fin.shells, fanfares:fin.fanfares, sparks:fin.sparks, bars:fin.bars, blend:fin.blend }, clouds:window.__blight.info().cloudsMade, ammo:window.__prisonwalls.mounts().map(m=>m.d.ammo), fires:window.__firesDuring, alive:d.enemies.filter(e=>!e.dead).length }; });
  check("breaking the first door starts the show: the bars slide in, the first room is the one he broke and the other is the second",S.t0.active&&S.t0.bars.every(b=>b==='12vh')&&S.t0.first&&S.t0.second&&S.t0.first!==S.t0.second,JSON.stringify(S.t0));
  check("the other door bursts open on its own (about 1.8 s in) and both mortars are out and rolled by about 6.5 s",S.seen.bothBroken>1.5&&S.seen.bothBroken<2.6&&S.seen.twoMounts<4&&S.seen.bothRolled<7,JSON.stringify({ broken:S.seen.bothBroken, mounts:S.seen.twoMounts, rolled:S.seen.bothRolled }));
  check("the fanfare sounds at about 6 s with a burst of gold sparks over the mortars",S.seen.fan>=5.9&&S.seen.fan<6.3&&S.fin.fanfares===1&&S.fin.sparks>=60,JSON.stringify({ fan:S.seen.fan, f:S.fin.fanfares, sparks:S.fin.sparks }));
  check("eight volleys fly (the first at 9 s, one every two seconds, the last at 23 s: each mortar four seconds apart), the mortars taking turns -- and ONLY those: the mortars' own fire is held, so each mortar's shot count is four",S.seen.v1>=8.9&&S.seen.v1<9.3&&S.seen.v8>22.9&&S.seen.v8<23.4&&S.fin.volleys===8&&S.fin.shells===8&&S.fires.every(n=>n===4),JSON.stringify({ v1:S.seen.v1, v8:S.seen.v8, volleys:S.fin.volleys, shells:S.fin.shells, fires:S.fires }));
  check("the shells burst into green mist (a cloud wherever one is not already) and the mist MADDENS the horde: dozens of mobs fight each other",S.clouds>=3&&S.maxMad>=20,JSON.stringify({ clouds:S.clouds, mad:S.maxMad }));
  check("the hero is held and untouchable the whole time (the 'w' key held down for the show: he did not move; his health never dropped)",Math.abs(S.hero[0]-S.hero0[0])<.01&&Math.abs(S.hero[1]-S.hero0[1])<.01&&S.minHp>=S.hp0,JSON.stringify({ hero:S.hero, hero0:S.hero0, minHp:S.minHp, hp0:S.hp0 }));
  check("the camera is the show's own: it moves through several different shots",S.cams>=4,String(S.cams));
  check("it ends at about 28 seconds: the bars slide away, the camera is handed back, every volley was free (both mortars full again) and the game ran on with the horde all along",S.seen.end>27.8&&S.seen.end<28.4&&!S.fin.active&&S.fin.done&&S.fin.bars.every(b=>b==='0px')&&S.alive>50&&S.ammo.every(a=>a>=6),JSON.stringify({ end:S.seen.end, ammo:S.ammo, alive:S.alive, bars:S.fin.bars }));
  const RL=await page.evaluate(()=>{ const d=window.__dd; const m0=window.__prisonwalls.mounts().map(m=>m.fires); const times=[[],[]]; for(let f=0;f<60*17;f++){ d.step(1/60,1); d.S.crystal=1e9; const cur=window.__prisonwalls.mounts().map(m=>m.fires); cur.forEach((n,i)=>{ if(n>m0[i]){ times[i].push(+((f+1)/60).toFixed(2)); m0[i]=n; } }); } const gaps=times.map(a=>a.slice(1).map((t,i)=>+(t-a[i]).toFixed(2))); return { times, gaps, rearm:window.__prisonwalls.REARM }; });
  check("and afterwards each mortar reloads for four seconds between its own shots (Matt: they fired so fast you missed what happened): the gaps between one mortar's shots are 4 s",RL.rearm===4&&RL.times.every(a=>a.length>=3)&&RL.gaps.every(g=>g.every(x=>x>=3.9&&x<=4.3)),JSON.stringify(RL));
  await page.context().close(); }
// ================= Enter skips it =================
{ const page=await open();
  await breakFirst(page); await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*3;i++){ d.step(1/60,1); d.S.crystal=1e9; } });
  await page.keyboard.press('Enter'); await sleep(200);
  const K=await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*8;i++){ d.step(1/60,1); d.S.crystal=1e9; } const i=window.__mortarshow.info(); return { active:i.active, done:i.done, skipped:i.skipped, t:i.t, broken:window.__prisonwalls.raw().map(q=>q.broken), mounts:window.__prisonwalls.mounts().length, bars:i.bars }; });
  check("Enter skips the show: it ends at once, both doors are open and both mortars are out",!K.active&&K.done&&K.skipped&&K.t<4&&K.broken.every(Boolean)&&K.mounts===2&&K.bars.every(b=>b==='0px'),JSON.stringify(K));
  await page.context().close(); }
// ================= not twice, not in a co-op hall, not with ?noshow =================
{ const page=await open('&noshow'); await breakFirst(page); const N=await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*3;i++){ d.step(1/60,1); d.S.crystal=1e9; } return window.__mortarshow.info().starts; }); check("with ?noshow the door just opens (no show: the older tests rely on it)",N===0,String(N)); await page.context().close(); }
{ const page=await open(); await page.evaluate(()=>{ window.__net.role=()=>'host'; }); await breakFirst(page); const C=await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*3;i++){ d.step(1/60,1); d.S.crystal=1e9; } return { starts:window.__mortarshow.info().starts, mounts:window.__prisonwalls.mounts().length }; }); check("in a co-op hall there is no cutscene (the door just opens and its mortar rolls out as before)",C.starts===0&&C.mounts===1,JSON.stringify(C)); await page.context().close(); }
{ const page=await open(); await breakFirst(page); await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60*30;i++){ d.step(1/60,1); d.S.crystal=1e9; } }); const R=await page.evaluate(()=>{ const sp=window.__prisonwalls.raw()[0].spot; const again=window.__mortarshow.onBreak(sp); return { again, starts:window.__mortarshow.info().starts, active:window.__mortarshow.info().active }; }); check("it plays once a run: after the one show a further break starts nothing",R.again===false&&R.starts===1&&!R.active,JSON.stringify(R)); await page.context().close(); }
// ================= Matt's music (build 384): his Power-Up track from its 7-second mark, the wall's music ducked under it =================
{ const ctx=await browser.newContext({viewport:{width:900,height:560}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","on"); localStorage.setItem("ddMusic","on"); }catch(e){} });
  const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e)));
  await page.goto("http://127.0.0.1:8997/?nogate&map=5",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__mortarshow&&window.__mortarshow.music&&window.__prisonwalls&&window.__prisonwalls.mounts&&window.__dd.map().id==='prison',null,{timeout:120000});
  await page.mouse.click(400,300); await sleep(500);
  const loaded=await page.evaluate(async()=>{ const b=await window.__mortarshow.loadMusic(); return b?+b.duration.toFixed(0):null; });
  await page.evaluate(()=>{ try{ window.__trainer.skip(); }catch(e){} const d=window.__dd; d.start(); d.step(1/60,5); window.__freeze=true; d.S.crystal=1e9; d.S.phase='wave'; window.__mortarwake.wake(); const w=window.__prisonwalls.raw().find(q=>!q.broken); w.locked=false; w.hit(1e9,new window.THREE.Vector3(w.spot.cx0,2,w.spot.cz0),new window.THREE.Vector3(0,0,-1)); });
  const M1=await page.evaluate(()=>{ const d=window.__dd; for(let i=0;i<60;i++){ d.step(1/60,1); d.S.crystal=1e9; } return window.__mortarshow.music(); });
  const M2=await page.evaluate(()=>{ const d=window.__dd; window.__mortarshow.skip(); for(let i=0;i<30;i++) d.step(1/60,1); return window.__mortarshow.music(); });
  check("the show plays Matt's track (185 s, from its 7-second mark) and lets it go when it ends",loaded>=180&&M1.loaded&&M1.playing&&M1.played===1&&M1.offset===7&&!M2.playing,JSON.stringify({ loaded, M1, M2 }));
  await ctx.close(); }
const realErrors=errors.filter(e=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(e)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed"); process.exit(results.every(Boolean)?0:1);
