// ===== 6/7 (97d-sixseven.js, 86k-sixseven.js, build 258): Matt's Storm Halberd, the named mythic polearm "6/7". Checked: the named table's piece (name, slot, stats, power), the Knight's hand shows the real model,
// every 6th swing throws lightning through up to 7 enemies for 70% of the hero's damage each (a chain the plain swing cannot reach), and it lies on the floor as itself.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8898);
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]});
const page=await browser.newPage({viewport:{width:1100,height:700}}); const errors=[]; page.on("pageerror",e=>errors.push(String(e)));
await page.goto("http://127.0.0.1:8898/?silent&nogate"); await page.waitForFunction(()=>window.__dd&&window.__heroes&&window.__weapons&&window.__mythic&&window.__sixseven&&window.__named&&window.__dd.heroModel(),null,{timeout:120000});
const r0=await page.evaluate(()=>{ const M=window.__mythic, it=M.normalize({tier:"named",named:"sixseven"}); return { it:it&&{name:it.name,slot:it.slot,named:it.named,rarity:it.rarity,stats:it.stats,power:it.power}, byName:M.id({name:"6/7",slot:"weapon"}), ids:window.__named.ids(), own:window.__named.own("sixseven"), model:window.__named.model({slot:"weapon",named:"sixseven"},"sword"), other:window.__named.model({slot:"weapon",named:"sixseven"},"staff") }; });
check("the named table has 6/7: a weapon, 28 damage, its power in words; the Knight's sword hand takes the real model, a staff hand the top staff",r0.it&&r0.it.name==="6/7"&&r0.it.slot==="weapon"&&r0.it.stats.dmg===28&&r0.it.rarity===5&&/6th swing/.test(r0.it.power)&&r0.byName==="sixseven"&&r0.ids.includes("sixseven")&&r0.own==="sword"&&r0.model==="named-sixseven"&&r0.other==="staff-battle",JSON.stringify(r0));
await page.evaluate(i=>window.__heroes.select(i),"knight"); await page.waitForFunction(()=>/Knight/.test(window.__dd.heroModel().label),null,{timeout:90000});
await page.evaluate(()=>{ const d=window.__dd, M=window.__meta; M.reset&&M.reset(); d.resetGear(); d.start(); d.step(1/60,10); const it=window.__mythic.normalize({tier:"named",named:"sixseven"}); M.giveItem(it); M.equip(it.id); });
for(let i=0;i<300;i++){ const ok=await page.evaluate(()=>{ window.__dd.step(1/60,2); const s=window.__weapons.state(); const m=window.__weapons.mounted(); return s.mounted&&m&&m.name==="named-sixseven"&&s.loaded.includes("named-sixseven"); }); if(ok) break; await new Promise(r=>setTimeout(r,60)); }
const r1=await page.evaluate(()=>{ const s=window.__weapons.state(), sd=window.__weapons.mounted().userData.sword; return { w:window.__weapons.look().w, mounted:s.mounted, loaded:s.loaded.includes("named-sixseven"), has:window.__mythic.has("sixseven"), tip:sd&&+sd.tipY.toFixed(2), grip:sd&&+((sd.gripY-(sd.tipY-sd.len))/sd.len).toFixed(2) }; });
check("equipped, the Knight holds the real Storm Halberd (named-sixseven), the power is active, the grip is near a third of the way up",r1.w==="named-sixseven"&&r1.mounted&&r1.loaded&&r1.has&&r1.grip>.3&&r1.grip<.42,JSON.stringify(r1));
// the strike itself: nine goblins in a line, the first in front of him, two units apart
const r2=await page.evaluate(()=>{ const d=window.__dd, X=window.__sixseven; for(const e of d.enemies){ e.dead=1; } d.enemies.length=0; d.setHero(0,10,0); d.step(1/60,5);
  const line=[0,1,2,3,4,5,6,7,8].map(i=>{ const e=d.spawn("goblin","N"); e.x=0; e.z=12+i*2.2; e.y=0; e.spd=0; e.hp=e.max=9999; e.dmg=0; e.atk=999; e.holdT=1e9; return e; }); window.__line=line; d.step(1/60,2);
  const before=line.map(e=>e.hp); const res=X.strike(d.hero.x,d.hero.y||0,d.hero.z,0,100); const lost=line.map((e,i)=>+(before[i]-e.hp).toFixed(1)); return { n:res.hits.length, segs:res.segs.length, lost }; });
check("the strike takes the nearest mob in front, then jumps down the line to seven in all, 70 damage each of a 100 hit; the eighth and ninth are untouched",r2.n===7&&r2.segs===7&&r2.lost.slice(0,7).every(v=>v===70)&&r2.lost[7]===0&&r2.lost[8]===0,JSON.stringify(r2));
// the counter: real swings; only the 6th throws it, and it reaches far past the swing's own reach
const r3=await page.evaluate(async()=>{ const d=window.__dd, X=window.__sixseven, line=window.__line; X.reset(); d.setHero(0,10,0); d.setCam(0,.42,8); d.step(1/60,5); line.forEach(e=>{ e.hp=e.max=9999; e.x=0; e.z=[12,14.2,16.4,18.6,20.8,23,25.2,27.4,29.6][line.indexOf(e)]; });
  const seen=[]; for(let s=1;s<=6;s++){ d.hero.swingT=-1; d.setHero(0,10,0); d.swing(); for(let f=0;f<45;f++){ d.step(1/60,1); line.forEach((e,k)=>{ e.x=0; e.z=[12,14.2,16.4,18.6,20.8,23,25.2,27.4,29.6][k]; }); } seen.push({swing:s,swings:X.state().swings,fired:X.state().fired,far:+(9999-line[5].hp).toFixed(1),hpFirst:9999-line[0].hp}); } return seen; });
check("swings 1 to 5 throw nothing (the sixth mob, well out of reach, is unhurt); the 6th swing throws it and the sixth mob takes 70% of the hero's hit",r3.slice(0,5).every(x=>x.fired===0&&x.far===0)&&r3[5].fired===1&&r3[5].far>0,JSON.stringify(r3));
// on the floor: its own model, a storm-blue column
const r4=await page.evaluate(()=>{ const d=window.__dd; const it=window.__mythic.normalize({tier:"named",named:"sixseven"}); const l=d.dropLoot(it,3,14,true); return { has:!!l&&!!l.mesh, art:it.art||null }; });
check("dropped on the floor it is an item of its own with card art (the picture Matt sent)",r4.has&&/named\/sixseven\.jpg$/.test(r4.art||""),JSON.stringify(r4));
// ---- the hideout side (hideout build 53), through the game's overlay
await page.evaluate(()=>{ window.__dd.setHero(30,30); window.__hideout.open(); }); let f=null; for(let i=0;i<600&&!f;i++){ f=page.frames().find(x=>x.url().includes("hideout/index.html")); if(!f) await new Promise(r=>setTimeout(r,50)); }
await f.waitForFunction(()=>typeof namedRecord==="function"&&typeof NAMED_MYTHICS!=="undefined"&&typeof pieceFromForged==="function",null,{timeout:120000});
const h=await f.evaluate(async()=>{ const N=NAMED_MYTHICS.sixseven; let rec=null; for(let i=0;i<300&&!rec;i++){ const r=namedRecord("weapon"); if(r.named==="sixseven") rec=r; }
  const piece=rec?pieceFromForged(rec):null; const art=N?await fetch(N.art).then(r=>r.status):0, glb=await fetch(NAMED_3D_DIR+"sixseven.glb.txt").then(r=>r.status);
  return { entry:!!N&&N.name==="6/7"&&N.type==="weapon"&&N.stats.dmg===28, has3d:NAMED_3D.has("sixseven"), rolled:!!rec, procd:rec&&rec.procd, primary:rec&&rec.primary, named3d:piece&&piece.named3d, pname:piece&&piece.name, art, glb, build:HIDEOUT_BUILD }; });
check("the hideout knows 6/7: a named weapon entry, its card art and 3D model load, the forge's weapon proc can roll it (proc'd, +35% on its damage), and a rolled piece shows the 3D model",h.entry&&h.has3d&&h.rolled&&h.procd&&h.primary==="dmg"&&h.named3d==="sixseven"&&h.pname==="6/7"&&h.art===200&&h.glb===200&&h.build>=53,JSON.stringify(h));
const realErrors=errors.filter(e=>!/Failed to load resource|favicon/i.test(e)&&!/net::ERR|hideout\/gear|fonts\.googleapis/i.test(e)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
