// ===== A SET WEAPON ON DISPLAY IS ITS REAL 3D MODEL (hideout build 77). Matt, with the Void warhammer and staff lying on a table as flat pictures: "this is the warhammer of the void why wont it show its 3d stand up
// version on the table". Checked: the four Void weapons (sword, staff, polearm, bow) each get their model from the game; put on the floor they stand up in their column of light, turning (no flat picture); their
// shapes are re-built in the hideout's own arrays (the game's are a different JS realm: GL_INVALID_ENUM on every draw -- the graphics card drew nothing); on a table spot (a size) they stand at most ~1.4 x that
// size tall; the placing ghost keeps its picture; a plain weapon with no set model keeps its picture too; no GL errors while all of that draws.
import { chromium } from "playwright"; import { serve } from "./serve.mjs";
const server=await serve(8995,{dist:process.env.DIST||"./dist"});
const results=[]; const check=(n,ok,d)=>{ results.push(ok); console.log((ok?"PASS ":"FAIL ")+n+(d?"  -> "+d:"")); };
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const errors=[]; let glErrors=0;
const ctx=await browser.newContext({viewport:{width:1100,height:700}}); await ctx.addInitScript(()=>{ try{ localStorage.setItem("ddMapsCleared","9"); localStorage.setItem("ddSound","off"); }catch(e){} });
const page=await ctx.newPage(); page.on("pageerror",e=>errors.push(String(e))); page.on("console",m=>{ if(/GL_INVALID|WebGL: INVALID/.test(m.text())) glErrors++; });
const STORE=[]; await page.route("**/api/hideout/gear",async r=>{ const req=r.request(); const H={"access-control-allow-origin":"*"}; if(req.method()==="POST"){ const b=JSON.parse(req.postData()||"{}"); const item=Object.assign({id:"p"+STORE.length,at:Date.now()},b); STORE.push(item); await r.fulfill({status:200,contentType:"application/json",headers:H,body:JSON.stringify({item})}); } else await r.fulfill({status:200,contentType:"application/json",headers:H,body:JSON.stringify({items:STORE})}); });
await page.goto("http://127.0.0.1:8995/?silent&nogate",{timeout:120000}); await page.waitForFunction(()=>window.__dd&&window.__meta&&window.__hideout,null,{timeout:120000});
await page.evaluate(()=>{ try{ window.__trainer.skip(); }catch(e){} window.__dd.start(); window.__dd.step(1/60,5); window.__hideout.open(); });
let f=null; for(let i=0;i<600&&!f;i++){ f=page.frames().find(x=>x.url().includes("hideout/index.html")); if(!f) await sleep(50); }
await f.waitForFunction(()=>window.__onebag&&typeof weaponTemplate==='function'&&typeof pollDroppedGear==='function',null,{timeout:120000}); await sleep(600);
const L=[['Mythic Sword of the Void','sword','sword-void'],['Mythic Staff of the Void','staff','staff-void'],['Mythic Polearm of the Void','polearm','polearm-void'],['Mythic Bow of the Void','bow','bow-void']];
const names=await f.evaluate(L=>L.map(([n,look])=>window.__onebag.weaponModel(pieceFromCarried({id:'x',name:n,slot:'weapon',rarity:5,lvl:20,stats:{dmg:20},tier:5,setId:'void',look}))),L);
check("the four Void weapons each resolve to their own model from the game: sword-void, staff-void, polearm-void, bow-void",JSON.stringify(names)===JSON.stringify(L.map(x=>x[2])),JSON.stringify(names));
L.forEach(([n,look],i)=>STORE.push({id:'w'+i,kind:'carried',type:'weapon',tier:'epic',name:n,payload:{id:'w'+i,name:n,slot:'weapon',rarity:5,lvl:20,stats:{dmg:20},tier:5,setId:'void',look},x:(i-1.5)*2.4,y:0.4825,z:-2.2,ry:0,droppedBy:'test',at:Date.now()}));
STORE.push({id:'plain',kind:'carried',type:'weapon',tier:'rare',name:'Plain Broadsword',payload:{id:'plain',name:'Plain Broadsword',slot:'weapon',rarity:2,lvl:3,stats:{dmg:3},tier:1},x:0,y:0.4825,z:-5,ry:0,droppedBy:'test',at:Date.now()});
await f.evaluate(()=>{ pollDroppedGear(); }); let st=null; for(let i=0;i<60;i++){ await sleep(500); st=await f.evaluate(()=>[...worldGear.values()].map(v=>({ id:v.data&&v.data.id, spin:v.group.children.some(c=>c.userData&&c.userData.rate), meshes:(()=>{ let n=0; v.group.traverse(o=>{ if(o.isMesh&&!o.userData.plinth&&o.geometry.index) n++; }); return n; })(), spr:v.group.children.filter(c=>c.isSprite).length }))); if(st.filter(s=>s.spin).length>=4) break; }
const void4=(st||[]).filter(s=>/^w\d$/.test(s.id)), plain=(st||[]).find(s=>s.id==='plain');
check("on the floor the four Void weapons stand as real 3D models, turning (a model with shapes in it, not a flat picture)",void4.length===4&&void4.every(s=>s.spin&&s.meshes>0),JSON.stringify(void4));
check("a plain weapon with no set model keeps its picture (as in the hall)",plain&&!plain.spin&&plain.meshes===0||plain&&!plain.spin,JSON.stringify(plain));
const realm=await f.evaluate(()=>{ let ok=true, n=0; for(const v of worldGear.values()) v.group.traverse(o=>{ if(o.isMesh&&o.userData&&!o.userData.plinth&&o.geometry.index){ n++; const p=o.geometry.attributes.position.array, ix=o.geometry.index.array; if(!(p instanceof Float32Array)||!(ix instanceof Uint16Array||ix instanceof Uint32Array)) ok=false; } }); return { ok, n }; });
check("their shapes are re-built in the hideout's own arrays (the game's would be a different realm and draw nothing)",realm.ok&&realm.n>0,JSON.stringify(realm));
const tbl=await f.evaluate(async()=>{ const piece=pieceFromCarried({id:'t',name:'Mythic Staff of the Void',slot:'weapon',rarity:5,lvl:20,stats:{dmg:20},tier:5,setId:'void',look:'staff'}); const g=makeGearStandGroup(piece,false,0.5); scene.add(g); for(let i=0;i<60;i++){ await new Promise(r=>setTimeout(r,200)); if(g.children.some(c=>c.userData&&c.userData.rate)) break; } g.updateMatrixWorld(true); const spin=g.children.find(c=>c.userData&&c.userData.rate); const bb=spin?new THREE.Box3().setFromObject(spin):null; const ghost=makeGearStandGroup(piece,true,0.5); scene.add(ghost); await new Promise(r=>setTimeout(r,1500)); const ghostSpin=ghost.children.some(c=>c.userData&&c.userData.rate); scene.remove(g); scene.remove(ghost); return { has:!!spin, h:bb?+(bb.max.y-bb.min.y).toFixed(2):null, w:bb?+Math.max(bb.max.x-bb.min.x,bb.max.z-bb.min.z).toFixed(2):null, ghostSpin }; });
check("on a table spot (room for 0.5) a staff stands upright at most ~1.4 x that tall (and narrower than the spot), and the placing ghost keeps its picture",tbl.has&&tbl.h>.25&&tbl.h<=.75&&tbl.w<=.5&&!tbl.ghostSpin,JSON.stringify(tbl));
await sleep(1500);
check("no GL errors while the models draw (GL_INVALID_ENUM was every draw call before the shapes were re-built)",glErrors===0,String(glErrors));
const realErrors=errors.filter(x=>!/Failed to load resource|favicon|net::ERR|hideout\/gear|fonts\.googleapis/i.test(x)); check("no page errors",realErrors.length===0,realErrors.slice(0,3).join(" | "));
await browser.close(); server.close(); console.log(results.filter(Boolean).length+"/"+results.length+" passed");
