// the four new ballistas on the bench floor (map 1, z 66): Marks I..IV in a row, each panned a little at a goblin off its heading, the last tilted at a drake
import { chromium } from "playwright"; import { serve } from "../serve.mjs";
const SP=process.env.SP; const server=await serve(8937,{dist:SP+"/dist"});
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const page=await browser.newPage({viewport:{width:900,height:560}}); const errs=[]; page.on("pageerror",e=>errs.push(String(e)));
await page.goto("http://127.0.0.1:8937/?silent&nogate"); await page.waitForFunction(()=>window.__dd,null,{timeout:120000}); await page.evaluate(()=>{ try{ localStorage.setItem("ddMapsCleared","5"); }catch(e){} });
await page.goto("http://127.0.0.1:8937/?silent&nogate&map=1"); await page.waitForFunction(()=>window.__dd&&window.__defglb&&window.__dd.heroModel()&&window.__dd.mobModel("goblin"),null,{timeout:120000});
const shot=async(name,hideHero)=>{ await page.evaluate((hide)=>{ document.getElementById("hud").style.display="none"; window.__freeze=true; if(hide){ const d=window.__dd; const at=new THREE.Vector3(d.hero.x,d.hero.y,d.hero.z); d.scene.children.forEach(o=>{ let sk=false; o.traverse(m=>{ if(m.isSkinnedMesh) sk=true; }); if(sk&&o.position.distanceTo(at)<.01){ o.visible=false; o.userData.hidden=true; } }); } },!!hideHero); await page.waitForTimeout(250); await page.screenshot({path:SP+"/parts/shots/"+name+".png",timeout:120000}); await page.evaluate(()=>{ window.__dd.scene.children.forEach(o=>{ if(o.userData.hidden){ o.visible=true; delete o.userData.hidden; } }); window.__freeze=false; }); };
const look=(hx,hz,yaw,pitch,dist)=>page.evaluate(([hx,hz,yaw,pitch,dist])=>{ const d=window.__dd; d.setHero(hx,hz,yaw); d.hero.y=0; d.setCam(yaw,pitch,dist); d.step(1/60,30); },[hx,hz,yaw,pitch,dist]);
await page.evaluate(()=>{ window.__meta.reset(); window.__dd.resetGear(); window.__dd.start(); window.__dd.step(1/60,10); for(let l=2;l<=4;l++) window.__defglb.ensure('harpoon',l); });
await page.waitForFunction(()=>{ const l=window.__defglb.list().harpoon||[]; return l[0]&&l[1]&&l[2]&&l[3]; },null,{timeout:120000});
const row=await page.evaluate(()=>{ const d=window.__dd; d.addMana(9000); d.setHero(0,74,Math.PI); d.hero.y=0; d.step(1/60,5); const out=[]; for(let k=0;k<4;k++){ const x=(k-1.5)*3.4; const t=d.place('harpoon',x,66,Math.PI); if(!t) continue; for(let u=1;u<=k;u++) d.upgrade({x:t.x,z:t.z}); out.push({lvl:t.lvl,x:t.x,z:t.z}); const e=d.spawn('goblin','N'); e.hp=1e9; e.spd=0; e.x=t.x+7*Math.sin(t.rot+.1); e.z=t.z+7*Math.cos(t.rot+.1); e.userData={t:out.length-1}; }
  d.step(1/60,80); for(const e of d.enemies){ const t=d.defs[e.userData&&e.userData.t]; if(t){ e.x=t.x+7*Math.sin(t.rot+.1); e.z=t.z+7*Math.cos(t.rot+.1); } } d.step(1/60,60); return out.map(o=>({...o,lvl:d.defs.find(t=>t.x===o.x&&t.z===o.z).lvl})); });
console.log(JSON.stringify(row));
await look(0,75,Math.PI,.36,9.5); await shot("ballista-row",true); await look(-3.4,70.5,Math.PI*.8,.18,5.5); await shot("ballista-close",true);
const tilt=await page.evaluate(()=>{ const d=window.__dd; for(const e of d.enemies) e.dead=true; d.step(1/60,5); const t=d.defs[3]||d.defs[0]; const dr=d.spawn('drake','N'); dr.hp=dr.max=1e6; dr.spd=0; for(let i=0;i<150;i++){ dr.x=t.x; dr.z=t.z-8; dr.y=4.5; d.step(1/60,1); } return {pitch:+(t.pitch||0).toFixed(2)}; });
console.log(JSON.stringify(tilt)); await look(3.4,72,Math.PI*.72,.12,6); await shot("ballista-tilt",true);
console.log("errors:",errs.join(" | ")||"none"); await browser.close(); server.close();
