// the Void blade in the knight's hand, close; the four halos with their light columns and goblins walking through; a lash landing
import { chromium } from "playwright"; import { serve } from "../serve.mjs";
const SP=process.env.SP; const server=await serve(8934,{dist:SP+"/dist"});
const browser=await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader"]}); const page=await browser.newPage({viewport:{width:1100,height:700}}); const errs=[]; page.on("pageerror",e=>errs.push(String(e)));
await page.goto("http://127.0.0.1:8934/?silent&nogate"); await page.waitForFunction(()=>window.__dd,null,{timeout:120000}); await page.evaluate(()=>{ try{ localStorage.setItem("ddMapsCleared","5"); }catch(e){} });
await page.goto("http://127.0.0.1:8934/?silent&nogate&map=1"); await page.waitForFunction(()=>window.__dd&&window.__weapons&&window.__voidset&&window.__heroes&&window.__dd.heroModel()&&window.__dd.mobModel("goblin"),null,{timeout:120000});
const shot=async(name,hideHero)=>{ await page.evaluate((hide)=>{ document.getElementById("hud").style.display="none"; window.__freeze=true; if(hide){ const d=window.__dd; const at=new THREE.Vector3(d.hero.x,d.hero.y,d.hero.z); d.scene.children.forEach(o=>{ let sk=false; o.traverse(m=>{ if(m.isSkinnedMesh) sk=true; }); if(sk&&o.position.distanceTo(at)<.01){ o.visible=false; o.userData.hidden=true; } }); } },!!hideHero); await page.waitForTimeout(250); await page.screenshot({path:SP+"/parts/shots/"+name+".png",timeout:120000}); await page.evaluate(()=>{ window.__dd.scene.children.forEach(o=>{ if(o.userData.hidden){ o.visible=true; delete o.userData.hidden; } }); window.__freeze=false; }); };
const look=(hx,hz,yaw,pitch,dist)=>page.evaluate(([hx,hz,yaw,pitch,dist])=>{ const d=window.__dd; d.setHero(hx,hz,yaw); d.hero.y=0; d.setCam(yaw,pitch,dist); d.step(1/60,30); },[hx,hz,yaw,pitch,dist]);
await page.evaluate(()=>{ window.__meta.reset(); window.__dd.resetGear(); window.__dd.start(); window.__dd.step(1/60,10); });
await page.evaluate(()=>window.__heroes.select("knight")); await page.waitForFunction(()=>/Knight/i.test(window.__dd.heroModel().label),null,{timeout:90000});
const hand=await page.evaluate(async()=>{ const d=window.__dd; window.__weapons.force("void"); for(let i=0;i<120;i++){ d.step(1/60,1); await new Promise(r=>setTimeout(r,0)); const s=window.__weapons.state(); if(/void/.test(s.key)&&s.mounted) break; } d.step(1/60,20); return window.__weapons.state(); });
console.log(JSON.stringify(hand)); await look(0,54,Math.PI*.8,.08,3.6); await shot("void-sword-hand"); await look(0,54,Math.PI*1.3,.06,3.0); await shot("void-sword-hand2");
// the halos: four across the bench floor (z 68), a goblin in each, the columns catching the light
const halos=await page.evaluate(()=>{ const d=window.__dd; window.__weapons.force(null); d.S.mana=99999; d.setHero(0,74,Math.PI); d.hero.y=0; d.step(1/60,5); const kinds=['zap','venom','ember','dazzle']; const out=[]; kinds.forEach((kind,j)=>{ const x=(j-1.5)*5.2, z=66; const before=d.defs.length; try{ d.placeDefAt(kind,x,z,0); }catch(e){} if(d.defs.length>before){ const nd=d.defs[d.defs.length-1]; out.push({kind,x:nd.x,z:nd.z}); for(let k=0;k<2;k++){ const e=d.spawn('goblin','N'); e.x=nd.x+(k?-1.2:1.4); e.z=nd.z+(k?1:-.6); e.hp=1e9; e.spd=0; } } }); d.step(1/60,80); return out; });
console.log(JSON.stringify(halos));
await look(0,75,Math.PI,.42,9); await shot("halo-columns",true); await look(-2.6,72,Math.PI*.85,.22,6); await shot("halo-column-close",true);
console.log("errors:",errs.join(" | ")||"none"); await browser.close(); server.close();
